### ISSUE TITLE
Esp32 blocked?

### ISSUE THREAD

**Issue by testHAtest** [technyon/nuki_hub#101]
Hello everyone, it happens every now and then that the esp32 seems to freeze, the red LED flashes very quickly but it doesn't let you do any lock action and the statuses don't update them, I try to access via browser and I reach it, wifi working and I access all the configurations, the mqq is connected but it seems blocked, I restart and all the states are updated and the lock commands work. What could it be? Thanks so much

**Comment by technyon** [comment]
The blinking is usually the logs written to the serial line. Can you try get logs ... either by enabling MQTT logging or by reading them over USB. You can use for example hterm, baud rate is 115200.

**Comment by technyon** [comment]
Also please recheck with release 8.1

**Comment by sebax80** [comment]
Thanks, I'm downloading it now and updating. further updates coming soon

**Comment by testHAtest** [comment]
![image](https://user-images.githubusercontent.com/88025386/216077263-1374bb51-3cda-448e-af68-3b507718ec8f.png)
:-)

**Comment by technyon** [comment]
So I can close the issue?

**Comment by testHAtest** [comment]
does it fix with 8.1? I'd like to know if you understood what the problem was.

**Comment by technyon** [comment]
There was an issue in the mqtt connection logic which was fixed in 8.1

**Comment by testHAtest** [comment]
Perfect and thank you for the fantastic work you do!!!! and yes you can close the issue!
