### ISSUE TITLE
"Enable keypad control via MQTT" Is not available

### ISSUE THREAD

**Issue by cpvbruno** [technyon/nuki_hub#103]
I don't see "Enable keypad control via MQTT" in advanced Nuki configuration, even though I have a Keypad 2.0 connected

**Comment by knorrre** [comment]
My guess is that it is a problem with the API.
https://developer.nuki.io/t/keypad-2-not-setting-has-keypad-flag-in-config-of-nuki-lock/19539

See also here:
https://github.com/technyon/nuki_hub/issues/42#issuecomment-1407374048

**Comment by cpvbruno** [comment]
Indeed it seems something related to the new keypad

**Comment by technyon** [comment]
I've updated the readme to make clear that at the time only Keypad 1.0 is supported. Let's hope that NUKI will provide an answer how to control Keypad 2.0.

**Comment by technyon** [comment]
... also closing the issue because until keypad 2.0 is supported this is (sadly) expected behaviour.
