### ISSUE TITLE
Nuki lock opening/closing operation register

### ISSUE THREAD

**Issue by amastrogiacomo1968** [technyon/nuki_hub#104]
Staying at home I happened to hear that the Nuki lock opened the door without anyone having given the command, I changed the password immediately but the thing recurs from time to time.
Is there any way to track open/close commands and maybe even which user sent the command?
Thank you

ps Not a real problem (I hope) but more of an implementation request

**Comment by technyon** [comment]
You're not at all using the Nuki App? I'd think it's kind of essential to use the lock. I can't tell you very much about tracking in home assistant since I'm not using it. But there are a few HA users around who maybe can help you.

**Comment by amastrogiacomo1968** [comment]
Why do you say it is essential? Apart from the initial configuration, I haven't used it anymore but I do everything via Home Assistant, if I really need to go via the web (but first I have to reconnect the Nuki bridge which is now resting in its box).

**Comment by technyon** [comment]
There are a lot of settings that can be configured via the app, firmware upgrades, connecting accessories like fobs or a door sensor. If it works for you no worries.

**Comment by amastrogiacomo1968** [comment]
I "played" with the configurations at the beginning but it's been a long time now that I haven't changed anything (only the password the other day for the ghost openings of the lock), perhaps the only thing is the updates

**Comment by mundschenk-at** [comment]
There is a log you can access via the official app, you should see what user or program caused the unlock event.

**Comment by amastrogiacomo1968** [comment]
Thanks, I didn't remember there was the log thanks

**Comment by alexdelprete** [comment]
Check also if you created some scripts/automations in HA...if the device is only controlled via HA, it means ONLY some HA action/script/event/automation triggered the command.

**Comment by amastrogiacomo1968** [comment]
> Check also if you created some scripts/automations in HA...if the device is only controlled via HA, it means ONLY some HA action/script/event/automation triggered the command.

I just have a script that invokes lock opening no automation; I have automations that block the lock (for example when arming the burglar alarm).
Is there any way to track who and when ran the opening script? Other than putting it in the configuration history? Thank you

**Comment by mundschenk-at** [comment]
You should see it in your HA logbook. Also you can see the last few script executions via traces (Automations & Scenes / Scripts and then Traces in the dots menu for the script).

**Comment by amastrogiacomo1968** [comment]
> You should see it in your HA logbook. Also you can see the last few script executions via traces (Automations & Scenes / Scripts and then Traces in the dots menu for the script).

I didn't know that in the trace there was also the user id that called the script, this thing is very interesting

**Comment by technyon** [comment]
Can this be closed?

**Comment by amastrogiacomo1968** [comment]
Yes
