### ISSUE TITLE
Nuki Keypad 2.0 support?

### ISSUE THREAD

**Issue by NdR91** [technyon/nuki_hub#112]
First of all, thank you for this great work @technyon.

Do you have on road map the Nuki Keypad 2 support? 

Thank you!

**Comment by technyon** [comment]
No, because there's no documentation available.

See here:
https://developer.nuki.io/t/keypad-2-not-setting-has-keypad-flag-in-config-of-nuki-lock/19539/3

Noone answering unfortunately.

**Comment by NdR91** [comment]
Thank you for the feedback. 

Hope to someone answer then!

Thank you again!

**Comment by mundschenk-at** [comment]
@technyon They have now updated the documentation it seems.

**Comment by Eyal51** [comment]
@technyon I appreciate the work you're doing

**Comment by technyon** [comment]
I will look into it as soon as I receive my 2.0 keypad.

**Comment by bcutter** [comment]
Let me/us other KP 2.0 users know once I/we can test something 👍
