### ISSUE TITLE
Wrong default settings in "Advanced NUKI Configuration"

### ISSUE THREAD

**Issue by bcutter** [technyon/nuki_hub#114]
_(Everything being said at https://community.home-assistant.io/t/nuki-hub-firmware-for-the-esp32/417572/218)_

Nuki Hub set up with firmware 8.4 gives this as default:

![grafik](https://user-images.githubusercontent.com/13799156/216846825-2d045e4d-9cda-446e-8042-e7d11998d845.png)

Result: spamming like crazy (bottom one):
![grafik](https://user-images.githubusercontent.com/13799156/216846856-97244623-dbb3-463f-a6b2-a114efa95092.png)

Messages seem to come down to a normal/comparable amount once the settings have been adjusted.

No idea when this was introduced, somewhere between 7.2 and 8.4, possibly even in latest 8.4?

**Comment by mundschenk-at** [comment]
@technyon, I can confirm this for a newly flashed & erased device via the Web Installer:
<img width="883" alt="image" src="https://user-images.githubusercontent.com/6943905/216847533-0ac74110-e9a3-45ab-b767-c08c8d49aa67.png">

I am assuming this has been introduced with the refactoring of the web interface in 8.4.

**Comment by technyon** [comment]
Accidentally moved some code instead of copying it. Fixed in 8.5.
