### ISSUE TITLE
Config for Homeassistant

### ISSUE THREAD

**Issue by lukes-ha** [technyon/nuki_hub#12]
This is just a little help, not a question.
I have the nuke v3
To use the mqtt lock in home assistant, i wrote this in the configuation.yaml:

mqtt:
  lock:
    - name: Haustür
      unique_id: 'nuki1'
      state_topic: 'nuki/lock/state'
      command_topic: 'nuki/lock/action'
      payload_lock: 'lock'
      payload_unlock: 'unlock'
      state_locked: 'locked'
      state_unlocked: 'unlocked'
      optimistic: false
      qos: 1
      retain: true
      value_template: "{{ value }}"

**Comment by technyon** [comment]
Thank you. It's a bit of a coincedence, but I've just released version 4.4 which support HA Auto Discovery.
