### ISSUE TITLE
Battery level occasionally dropping to 0

### ISSUE THREAD

**Issue by chatziko** [technyon/nuki_hub#121]
Hello,

I have connected Nuki to Home Assistant via the MQTT integration, with the default settings (it was discovered automatically). It generally works fine, with a small issue: the reported battery level occasionally jumpts to either 0% or 126% (normally it is 94%). See the plot below.

![image](https://user-images.githubusercontent.com/362089/218034838-2e97ea2e-f60b-42ff-9942-24e7f996757c.png)

Every time this happens, it is restored after exactly 10 minutes (I guess this is the update interval).
Not a big issue obviously, but it messes with some "low battery" automations.

**Comment by technyon** [comment]
Hi,

this most likely happens because the battery state is published, but querying from the lock was not successful. Will be addressed in the next release.

**Comment by chatziko** [comment]
Awsome, thanks for the quick response. Just updated to 8.8, let's see what happens...

**Comment by mundschenk-at** [comment]
I've seen this about two or three times per week, so we will have to monitor for a few days to ascertain the issue is definitely fixed.

**Comment by bcutter** [comment]
Exactly what I see and was wondering about too. Different lock types with different battery types.

![grafik](https://user-images.githubusercontent.com/13799156/218309587-b67584b4-e2ca-4139-aa49-5b34b7643bca.png)

The "return from zero" happens differently, for one lock after exactly 1 hour (which is my set battery state query interval) the other only few minutes.

**Comment by technyon** [comment]
@bcutter which firmware version is this?

**Comment by bcutter** [comment]
It changed during that time. Mainly 8.5 (updated now to 8.8).

**Comment by technyon** [comment]
It's one of the points that should be fixed in 8.8.

**Comment by chatziko** [comment]
2 days without a single drop since upgrading to 8.8, so this looks like fixed, many thanks!
Closing the issue, I'll reopen if it happens again.
