### ISSUE TITLE
Restart through http/mqtt command

### ISSUE THREAD

**Issue by bartsnijder** [technyon/nuki_hub#122]
My bluetooth link between hub and lock is sometimes broken which makes the lock uncontrollable through the hub. I recently have set the "Restart if bluetooth beacons not received" option so I should be safe from now on (to double check). However, since the lock opens the main entry I would like to have a second fallback. Is there a http/mqtt command to restart the Nuki hub manually. A broken bluetooth link is detectable through MQTT (eg commandresult = error), so I would like to be able to restart the hub manually when such situation would occur.
Thanks!

**Comment by technyon** [comment]
Set the "maintenance/reset" node to 1 to restart the ESP.

**Comment by bartsnijder** [comment]
That easy, thanks!
