### ISSUE TITLE
Update notification

### ISSUE THREAD

**Issue by knorrre** [technyon/nuki_hub#125]
Hello,
is it possible to receive an update notification from Nuki Hub via Home Assistant? This way you don't always have to check here in the releases.
Thanks!

**Comment by Eyal51** [comment]
+1

**Comment by mundschenk-at** [comment]
You could just use  https://www.home-assistant.io/integrations/github/

**Comment by technyon** [comment]
Hi,

As mentioned I think this should be solved outside of the firmware. Thanks for pointing out the github integration.

**Comment by technyon** [comment]
Closing, as recommeded please use

https://www.home-assistant.io/integrations/github/
