### ISSUE TITLE
Can't open the door, am I missing something ?

### ISSUE THREAD

**Issue by sator86** [technyon/nuki_hub#133]
Hello dear,
I thank you very much for this hack, it's work very well
I just have an issue with homeassistant, I can't open the door
I can lock and unlock it, but can't open it
on the interface I can see that it's not enabled 
![image](https://user-images.githubusercontent.com/55639966/222830863-6d27d0bb-c2c8-4b35-8df6-16f0b6e6cd15.png)
![image](https://user-images.githubusercontent.com/55639966/222830915-41058a74-f7e5-401c-9b6f-62990d19aaa6.png)

what can  I doo to making it open ?
thank you for your help

**Comment by technyon** [comment]
See issue #66

**Comment by sator86** [comment]
ah ok
it's working very well
thank you very much
