### ISSUE TITLE
Adding supported model to read.me 

### ISSUE THREAD

**Issue by Antexa** [technyon/nuki_hub#14]
Could be great to have the supported model list in the readme file. 

I can't figure out if its compatible with nuki 3.0 Pro or if the Nuki 3.0 is supported too.

However the right question I think: is this using bluetooth or wifi

**Comment by technyon** [comment]
Bluetooth. I have the regular Nuki 3.0, but the Pro is the same with an added Wifi module as far as I know, so it should be supported. Version 1.0 and 2.0 are also supported.

**Comment by Antexa** [comment]
👍 

Kinda not really obvious, thank you @technyon
