### ISSUE TITLE
Help Wanted: How to get Bluetooth signal strength sensor working

### ISSUE THREAD

**Issue by thor9898** [technyon/nuki_hub#140]
I've had this working for over a month now, but the Bluetooth signal strength has always been unknown and I can't find how to get it in the readme.md
Same happen with the WiFi signal strength, although this is not as important as the other.

![image](https://user-images.githubusercontent.com/58491644/223391671-02eb9fda-a69f-423d-b49f-abf19895e9e8.png)

**Comment by alexdelprete** [comment]
What version of HA and Nuki Hub?

Go in HA developer tools and post these two screenshots of the two sensors:

![image](https://user-images.githubusercontent.com/7027842/223427470-6cf4cd56-6156-473f-b958-2172e9d8d71c.png)

![image](https://user-images.githubusercontent.com/7027842/223427382-55ba951e-0648-4794-b452-ff6436e781ac.png)

Also, check MQTT data in the broker, and post the contents of these two topics highlighted in yellow:

![image](https://user-images.githubusercontent.com/7027842/223428752-3ede179c-8fc4-4776-84f1-2d58d7b29ab6.png)

**Comment by thor9898** [comment]
@alexdelprete Sorry i didnt provide the versions earlier, I have the latest release of HA and Nuki Hub.

![image](https://user-images.githubusercontent.com/58491644/223440931-7c5b4214-6181-4637-8201-a00baf8f5c83.png)
![image](https://user-images.githubusercontent.com/58491644/223441050-8b72c1ae-72c6-4f2c-a759-f5491b9d2a7c.png)

I don't know how to get to that last pic you uploaded, I'm very bad at mqtt. I have mosquitto broker addon, so if you guide me ill upload it asap

I don't know if this would work:

![image](https://user-images.githubusercontent.com/58491644/223444021-f409bb09-18fd-4f93-a360-838215598f9c.png)


![image](https://user-images.githubusercontent.com/58491644/223444211-6fc6e2e8-53c9-42a3-9353-fca4ca5096a3.png)

**Comment by alexdelprete** [comment]
> I don't know how to get to that last pic you uploaded, I'm very bad at mqtt. I have mosquitto broker addon, so if you guide me ill upload it asap

You need a tool like MQTT Explorer to navigate the MQTT broker. Install it and configure it.

Anyway, I already see some strange things: the nuki/lock/rssi and nuki/lock/wifiRssi topics have zero received msgs:

![image](https://user-images.githubusercontent.com/7027842/223462761-1059b6b6-e737-43d9-bae2-13e3f0c9317e.png)
![image](https://user-images.githubusercontent.com/7027842/223462788-5364d9bc-3d9e-4eb3-aeed-515f326044f2.png)

This means something not right at the broker level. Can you please show me how you configured the **MQTT NUKI Smartlock Path** on the Nuki Hub web UI?

![image](https://user-images.githubusercontent.com/7027842/223463318-1d00a7b1-6839-4620-82ef-c9949681d656.png)

**Comment by alexdelprete** [comment]
Also, please show me the subtopic of the lock config:

![image](https://user-images.githubusercontent.com/7027842/223464830-e793d1d1-82da-4a99-a4ff-97de90bad8ee.png)

**Comment by capandcamera** [comment]
I resolved my bluetooth one by changing the following setting in the MQTT & Network section

```RSSI Publish interval (seconds; -1 to disable)


My wifi still doesn't seem to publish an RSSI though but hopefully this helps you fix your bluetooth one atleast.

**Comment by thor9898** [comment]
@alexdelprete 
Subscribed topics:
nuki/battery/critical
10 most recently received message(s)
Received 10:42:02
QoS: 0
Payload: 0
Received 10:43:39
QoS: 0
Payload: 0
Received 10:45:40
QoS: 0
Payload: 0
Received 10:47:43
QoS: 0
Payload: 0
Received 10:50:19
QoS: 0
Payload: 0
Received 10:51:42
QoS: 0
Payload: 0
Received 10:53:52
QoS: 0
Payload: 0
Received 10:55:44
QoS: 0
Payload: 0
Received 10:56:06
QoS: 0
Payload: 0
Received 16:37:19
QoS: 0
Payload: 0

**Comment by thor9898** [comment]
@capandcamera Oh wow, that made it!! Even wifi is showing no!!!

![image](https://user-images.githubusercontent.com/58491644/223471791-068a72d1-eb78-4207-82d0-de7f36430545.png)

**Comment by alexdelprete** [comment]
> @capandcamera Oh wow, that made it!! Even wifi is showing no!!!
> 
> ![image](https://user-images.githubusercontent.com/58491644/223471791-068a72d1-eb78-4207-82d0-de7f36430545.png)
> 
> Thank you very much!!

You had it disabled (-1)?

**Comment by thor9898** [comment]
@alexdelprete yes, as I said I couldn't find info about how to enable it in the info.
Sorry if I took much of your time.

**Comment by alexdelprete** [comment]
> yes, as I said I couldn't find info about how to enable it in the info.
> Sorry if I took much of your time.

Oh no, I'm sorry because I didn't tell you about that basic setting first, I assumed you had already tried basic things. Bad assumption, sorry. :)

**Comment by thor9898** [comment]
@alexdelprete Yes it's updating. Now everything works fine right now :)
Thanks for your willingness to help me, I appreciate it, my Mediterranean brother :)

**Comment by alexdelprete** [comment]
"Puerta de casa..." leads me to think you're from Spain. :)

I'll reveal you one secret: I was born in Madrid. My father worked there for some years when I was a little kid. But I'm 100% italian (from Napoli). :)

**Comment by capandcamera** [comment]
> > My wifi still doesn't seem to publish
> 
> did you check data in the broker? if it is updating...

I can't see it at all in MQTT Explorer.
RSSi now appears under: nuki/lock/rssi
but I can't find wifiRssi anywhere (checked /lock and /maintenance

/maintenance only has 'uptime' and 'reset'

**Comment by alexdelprete** [comment]
Are you sure you're looking at the right nuki_hub topic in the broker? Did you change it in the options maybe? The default root topic is nuki_hub if I recall correctly, but it's customizable.

**Comment by capandcamera** [comment]
I cleared down the topic and restarted nuki_hub - The topic has been set to 'nuki' in config.
I just enabled MQTT logging to see if it was that causing some options to not appear, i can see log has appeared in the right topic but I do not get as much information as you have in your maintenance topic.
<img width="502" alt="Screenshot 2023-03-08 at 13 25 39" src="https://user-images.githubusercontent.com/79606905/223724843-56bbbb0a-b584-4d41-8c3d-3506a2b4f408.png">

my uptime in the maintenance topic also stays at 0 regardless of uptime - Is there a setting that i need to configure to allow maintenance reporting?

**Comment by alexdelprete** [comment]
You're using latest version, 8.16? This is really strange...here's a bit of my config in MQTT section:

![image](https://user-images.githubusercontent.com/7027842/223726905-42d21123-b148-4605-b0b1-f199fa456d61.png)

**Comment by capandcamera** [comment]
Settings are very similar, other than the network hardware section which i've left as was.
<img width="791" alt="Screenshot 2023-03-08 at 13 46 26" src="https://user-images.githubusercontent.com/79606905/223729128-7a1338df-47a7-41ae-876b-668c90b5cea5.png">

**Comment by alexdelprete** [comment]
You have the W5500? Maybe that's the difference...but let's wait for @technyon to step in.

**Comment by capandcamera** [comment]
Weirdly I don't, 
I'm using the Atom Lite (Non POE version) via Wi-Fi.

**Comment by mundschenk-at** [comment]
If `uptime` stays at `0`, you very likely have a reboot loop.

**Comment by capandcamera** [comment]
Thanks @mundschenk-at you were correct!  I've noticed 'Restart timer (minutes; -1 to disable)' was enabled to 1 minute. 
I'm not sure when this setting was changed but it then caused it to reboot before it managed to get a WifiRssi.

The topic is now showing and uptime is increasing!

**Comment by alexdelprete** [comment]
You said settings were similar to mine. :)

Fix the network hw setting. I can't understand how it is connecting, unless it fallsback automatically to wifi. Anyway you should set it at Wifi only.

**Comment by capandcamera** [comment]
> You said settings were similar to mine. :)
> 
> Fix the network hw setting. I can't understand how it is connecting, unless it fallsback automatically to wifi. Anyway you should set it at Wifi only.

I thought they were, i missed the darn - on that option. 

I'll correct the networking options now though!

**Comment by mundschenk-at** [comment]
> Fix the network hw setting. I can't understand how it is connecting, unless it fallsback automatically to wifi. Anyway you should set it at Wifi only.

I am pretty sure it does exactly that: It probes the given GPIO and falls back to WiFi if it doesn't detect the ethernet hardware.

**Comment by alexdelprete** [comment]
Probably, but since he has a wifi M5 Atom Lite...that setting is wrongly configured.

**Comment by technyon** [comment]
This option actually is the old method of detecting a W5500. If you connect ground to GPIO 26, it switches to W5500, otherwise it uses Wifi. And yes there's fallback Wifi if no W5500 is present. I'm actually thinking about removing the detect via GPIO logic, since there's also LAN8720 now and it doesn't really make sense anymore.

**Comment by thor9898** [comment]
I know this might not be the place to ask it but as it's a probably easy question for you guys I think it's easier to ask it in this already open issue than opening a new one only for this silly question.
In the system information where is the contact sensor status?

**Comment by technyon** [comment]
@thor9898 Please update to 8.17

**Comment by thor9898** [comment]
@technyon done already, should I be able to find it now?

**Comment by technyon** [comment]
I think I misread your question. 8.18 fixes a bug about home assistant auto discovery and the door sensor. Currently the door sensor doesn't show up in the system information page.
