### ISSUE TITLE
Battery Level

### ISSUE THREAD

**Issue by H0useman** [technyon/nuki_hub#15]
I miss the battery level in the mqtt information.

Is this just a problem for me or do others have it too?

I use mqtt in ioBroker and the nuki_hub.bin from 28.06. (4.5-testing because of the Wifi problem)

**Comment by H0useman** [comment]
<img width="1473" alt="Screenshot 2022-06-30 at 10 30 17" src="https://user-images.githubusercontent.com/88840903/176632978-86b05435-0177-403b-9cdf-cd6010a6d8d4.png">

**Comment by technyon** [comment]
It's actually a bug, and has been fixed in release 4.6
