### ISSUE TITLE
Can't use your coupon code anymore

### ISSUE THREAD

**Issue by shumilica** [technyon/nuki_hub#150]
Nuki site says:
It appears that this coupon has reached its referral limit and is no longer available.

Maybe you can regenerate one or make another account.

**Comment by technyon** [comment]
Hi, thanks for letting me know. I've updated the code.

**Comment by rforro** [comment]
Please update referral code, wanted to support you but it don't works.

**Comment by technyon** [comment]
Thanks for letting me know, the code is updated
