### ISSUE TITLE
delay issue

### ISSUE THREAD

**Issue by streetjumper16** [technyon/nuki_hub#153]
Hello,

i have a problem with the delay. When I click unlock in MQTT, it takes 3-8 seconds for the lock to open. the same with locking. does anyone have any tips on what could be wrong here?

**Comment by technyon** [comment]
Enable MQTT logs and check what's going on. Most likely, bluetooth communication doesn't work immediately, and the ESP has to retry to get the command to the lock. How far apart are the lock and the ESPß

**Comment by streetjumper16** [comment]
I have activated mqtt logging, how can I read the log now?  I'm brand new to Mqtt.  BT shows 61 dBm, there is a 25cm wall between the lock and the Nuki Hub.

**Comment by technyon** [comment]
Which home automation system are you using? You have to keep a history of the maintenance/log topic.

**Comment by streetjumper16** [comment]
I use Home Assistant with Mosquitto Broker.

**Comment by mundschenk-at** [comment]
I've answered in the HA forum thread.

**Comment by leranp** [comment]
Same here ,it can take more than 10 seconds some time.
I replaced the Nuki Bridge for this project because the bridge was having a lot of delays

**Comment by technyon** [comment]
I have no such delays. First of all, please upgrade to version 8.20.

Next, please post the content of the System information page. Last, I'd need logs, best serial but MQTT logs would do in this case I think.

**Comment by leranp** [comment]
> I have no such delays. First of all, please upgrade to version 8.20.
> 
> Next, please post the content of the System information page. Last, I'd need logs, best serial but MQTT logs would do in this case I think.

This is my the system information page:
```
NUKI Hub version: 8.20
run: true
deviceId: ******
mqttbroker: ***********
mqttport: 1883
mqttuser: ***
mqttpass: ***
mqttlog: true
lockena: true
mqttpath: nuki
openerena: false
mqttoppath: 
maxkpad: 
opmaxkpad: 
mqttca: 
mqttcrt: 
mqttkey: 
hassdiscovery: homeassistant
dhcpena: true
ipaddr: 
ipsub: 
ipgtw: 
dnssrv: 
nwhw: 5
nwhwdt: 26
rssipb: 60
hostname: nukihub
nettmout: -1
restdisc: false
resttmr: -1
rstbcn: -1
lockStInterval: 1800
configInterval: 3600
batInterval: 1800
kpInterval: 1800
kpEnabled: false
regAsApp: false
nrRetry: 10
rtryDelay: 100
crdusr: ***
crdpass: ***
pubauth: false
gpiolck: false
pubdbg: false
prdtimeout: -1
hasmac: false
macb0: 
macb1: 
macb2: 
MQTT connected: Yes
Lock firmware version: 3.5.12
Lock hardware version: 4.10
Lock paired: Yes
Lock PIN set: No
Lock has door sensor: No
Lock has keypad: No
Network device: WT32-ETH01
Uptime: 20 minutes
Heap: 112736
Stack watermarks: nw: 6176, nuki: 576, pd: 280
Restart reason FW: OTACompleted
Restart reason ESP: ESP_RST_SW: Software reset via esp_restart.
```


in the logs I can see:
```
Querying lock state: Lock action received: unlock
Lock action result: failed
Lock: Last command failed, retrying after 100 milliseconds. Retry 1 of 10
Querying lock state: Lock action result: failed
Lock: Last command failed, retrying after 100 milliseconds. Retry 2 of 10
Querying lock state: locked
Lock action result: success
Querying lock state: Querying lock state: Querying lock state: unlocked
Querying lock state: unlocked
```

**Comment by technyon** [comment]
Yes, as I suggested there are several retries before the lock action is executed. Not much I can do about it. Like I said check that the ESP is as close as possible (maybe just for testing try the other side of the wall), and maybe check for sources of RF interference.

**Comment by leranp** [comment]
> Yes, as I suggested there are several retries before the lock action is executed. Not much I can do about it. Like I said check that the ESP is as close as possible (maybe just for testing try the other side of the wall), and maybe check for sources of RF interference.

I think the problem was version 8.18, the delays are now better in the 8.20 version

**Comment by streetjumper16** [comment]
The lag is better for me too.  I can now also intercept the ring signal faster to create an automation, which was associated with the bridge with a strong delay through the Nuki Cloud
