### ISSUE TITLE
Implement LWT with nuki hub

### ISSUE THREAD

**Issue by ralle12345** [technyon/nuki_hub#155]
Hi,

I would like to request the implemtation of the MQTT LWT feature in the nuki hub to detect the MQTT disconnect of the nukihub from the broker. See here: https://www.hivemq.com/blog/mqtt-essentials-part-9-last-will-and-testament/

If it's already present and I didn't find it, just close this issue 😄 

Thanks!

**Comment by technyon** [comment]
See release 8.20

**Comment by ralle12345** [comment]
I found the new topic. Thanks!  

Ihave one more request though. The topic is not announced in the homeassistant auto discovery mechanism. Could you add it there as well?

**Comment by technyon** [comment]
Check Release 8.21.
