### ISSUE TITLE
Feature request: Create switch/button in Home Assistant for restarting NUKI Hub

### ISSUE THREAD

**Issue by bcutter** [technyon/nuki_hub#158]
Can we have an out of the box switch (or **button** meanwhile) entity in Home Assistant for restarting the NUKI hub?

---

I had some situations where this was needed, physical access to the ESP was not possible and logging in to the web interface (open MQTT/network settings and click save to trigger restart) is only possible for me (due to the access protection) but still neither handy nor quickly.

Latest occurrence (which made me finally write this FR) by the way: SL died (Bluetooth died), pulled the battery. After that, NUKI hub did not reconnect automatically within few minutes - at least changing settings (LED off/on etc.) from HA had no effect on the SL. For that a quick restart sent from HA would just be perfect.

**Comment by technyon** [comment]
Hi, you can already connect with MQTT explorer and trigger a reboot by setting the maintenance/reset node to 1.

**Comment by bcutter** [comment]
OK that's good news - and a welcome prerequisite for the target of having an entity for that in HA.

Step 1: how to template this? (MQTT noob asking)

Step 2: why not making this button available out of the box?

**Comment by desheh** [comment]
You can easily setup a button (trigger the "MQTT: Publish" service) that will publish an MQTT packet with topic: `nuki/maintenance/reset` with payload `1`.

**Comment by bcutter** [comment]
> You can easily setup a button (trigger the "MQTT: Publish" service) that will publish an MQTT packet with topic: `nuki/maintenance/reset` with payload `1`.

How?

To be precise: not talking bout a simple GUI button but a `button.nuki_hub_restart` **entity**.

If one could provide a full working example, that would be helpful I guess.

**Comment by benedikt-bartscher** [comment]
You can either template the button with Home Assistant (https://www.home-assistant.io/integrations/template/) manually or extend nuki_hub by adding mqtt autodiscovery for the button

**Comment by bcutter** [comment]
Sorry, still no news - I'm really looking for a _working example_ on how to achieve this.

**Comment by mundschenk-at** [comment]
@bcutter I don't want to sound harsh, but you could look that up in HA's [MQTT documentation](https://www.home-assistant.io/integrations/button.mqtt/).

**Comment by technyon** [comment]
Check Release 8.21.

**Comment by bcutter** [comment]
![grafik](https://user-images.githubusercontent.com/13799156/229908592-3f70701c-07ec-4030-bf1b-f8d2c3577f34.png)

Veeeeery nice. Two new entites per NUKI hub! 🎉🥳

And the restart works like a charme. Thank you so much!
