### ISSUE TITLE
Reflect device status in home assistant entity

### ISSUE THREAD

**Issue by leranp** [technyon/nuki_hub#166]
Hi,

Thank you for your project!
Recently my ESP device was disconnected from the network, but the automation in HA didn't sent me a message about it, so i tried to see why and saw that the device in HA isn't going to "unavailable" when it's going offline, Do I miss something?
It looks like there is no "Offline/Online" MQTT sensor that switches the device to unavailable state

**Comment by technyon** [comment]
Which firmware version are you on?

**Comment by mundschenk-at** [comment]
@technyon That's something for the auto-discovery rewrite.

**Comment by technyon** [comment]
Well yes, but the latest firmware has a connection state topic (including auto discovery) which does exactly this.

**Comment by mundschenk-at** [comment]
No, not in the sense that the OP likely means. In HA, when a device becomes unavailable, the state of the entities changes to `unavailable` (or `unknown` with slightly different semantics). To get that behavior with MQTT, the discovery payload has to include some additional keys.

**Comment by technyon** [comment]
ok I see

**Comment by yasars** [comment]
same problem here, yes, I also have after a restart that sometimes the status is unavailable ... after a renewed restart it works again ... I'll try with the automation if I can do something that it reboots again if unavailable ... so it would be on small fixx....

**Comment by mundschenk-at** [comment]
> same problem here, yes, I also have after a restart that sometimes the status is unavailable ... after a renewed restart it works again ... I'll try with the automation if I can do something that it reboots again if unavailable ... so it would be on small fixx....

Please open your own issue, this is the opposite of what the OP wants (explicitly setting the state to `unavailable` because currently it isn't).

**Comment by iranl** [comment]
After merging #292 all entities in Home Assistant discovery now include the activity topic which (in conjunction with LWT) ensures all entities (not just the lock entity) become unavailable when the device goes offline/becomes unavailable to the MQTT broker for whatever reason. Tested in my own build including #292 by pulling the USB power cable from the wall.

I propose this issue is marked as fixed by #292 and closed.

**Comment by technyon** [comment]
ok, closing this
