### ISSUE TITLE
Nuki App/Features still usable with Nuki Hub?

### ISSUE THREAD

**Issue by r748** [technyon/nuki_hub#172]
I apologize for this stupid question, but from the Readme it isn't quite clear to me:

We currently have 2 Smart Locks 2.0 each connected to a Nuki Bridge. If I replace the Bridges with 2 ESP32 Nuki Hubs, will the lock just be controllable by MQTT or will I also still be able to use the Nuki App for features like lock, unlock, auto unlock, firmware updates (of the Smart Locks and Keypads), etc.?

**Comment by mundschenk-at** [comment]
You would definitely still need the app for firmware updates and adding accessories (like the door sensor). Most of the settings can be configured via MQTT (though auto-lock/-unlock would need to go through your home automation system, I don't think there is any way to configure those native automations via Nuki Hub).

**Comment by technyon** [comment]
NUKI Hub can do a lot, but not everything, I'd say you still need the app ... but it's easy enough to setup. It's not possible to update the lock firmware via NUKI Hub, also as mentioned configuring accessories has to be done via the app.

**Comment by r748** [comment]
Thanks for the replies.

Okay, so that means that if I want to be able to control my Nuki locks with MQTT commands through my home automation system (ioBroker), but at the same time want to keep using Nuki features like auto unlock or firmware update of the lock, then I have to run Nuki Hub and Nuki Bridge in parallel, correct?

**Comment by technyon** [comment]
Sorry for the late answer, I lost track of this issue. Yes, it works the way you described it.
