### ISSUE TITLE
No Nuki in Home Assistant

### ISSUE THREAD

**Issue by alkertrazz** [technyon/nuki_hub#173]
Hey guys,

first of all thank you for all of your work!

Unfortunately it isn't possible for home assistant to discover my Nuki 3.0. MQTT is connected, the lock is paired but everything what I try fails.

**Comment by flotomation** [comment]
Could you check that you configured the auto config topic?

<img width="772" alt="image" src="https://user-images.githubusercontent.com/129587589/231846201-5c4fb76c-eed2-429f-8aa9-172e4b642893.png">

**Comment by alkertrazz** [comment]
Hey flotomation, 
thx this were the problem. I didn't read all of the settings because I thought this advanced settings were only for SSL.

**Comment by platini76** [comment]
I have the same problem, all is configured. mqtt is connected... discovery topic is configured.. but ... no entity found, can someone help me?

**Comment by craigrouse** [comment]
I have the same issue as @platini76, and can't figure out why autodiscovery isn't working
