### ISSUE TITLE
Can't control two nuki locks separately in Home Assistant

### ISSUE THREAD

**Issue by Wpeter86** [technyon/nuki_hub#178]
Hello,
I have two Nuki Lock 3.0, each of which I have connected to an ESP32 flashed with nuki_hub (version 8.22). Both are also correctly detected individually in Home Assistant via MQTT. However, both locks are always opened or closed, if i try to control one of them in Home Assistant. In addition, the same state is displayed for both devices (last transmitted state).

Do I have to change something in nuki_hub  to prevent this?

Thanks!

**Comment by Wpeter86** [comment]
Found my mistake:
Had to rename "MQTT smart lock path" under "Basic Nuki Configuration". After that everything started working as excepted.

**Comment by technyon** [comment]
Yes, maybe I'll add it to the readme, it's not that obvious you have to change it.

**Comment by mundschenk-at** [comment]
Yes, with two locks you obviously need separate MQTT topics.
