### ISSUE TITLE
Feature request: update Nuki Hub firmware via HA

### ISSUE THREAD

**Issue by desheh** [technyon/nuki_hub#182]
I suppose one could go about multiple ways to implement this; off the top of my head: have an MQTT message listener that will send an update file payload (is that even possible?), make Nuki Hub be compatible with something like ESPHome, etc.

Also, could be nice to receive some notification on version update (like HACS does).

**Comment by technyon** [comment]
Hi,

Implementing such a feature is complicated and time-consuming. Considering this is a slight gain in convenience vs. a lot of time not spent on more important features, this is not on my to-do list.
