### ISSUE TITLE
Feature request: Control permission via MQTT

### ISSUE THREAD

**Issue by Eguar-rc** [technyon/nuki_hub#183]
Lock permissions, users, keypad, fob.
Controlling users or devices remotely would be useful.

**Comment by technyon** [comment]
What exactly is your use case. There a lot of things covered by the ble API, adding all of those in an MQTT API could prove difficult. Do you just want to enable/disable existing authorizations?

**Comment by Eguar-rc** [comment]
Thanks for your answer.

 

I am interested in being able to cancel access to a specific FOB, for example if I am outside my network and want to prevent the entry of a guest. 

Effectively I want to enable/disable existing authorizations.

 

 

De: Jan-Ole Schümann ***@***.***> 
Enviado el: domingo, 30 de abril de 2023 21:51
Para: technyon/nuki_hub ***@***.***>
CC: Eguar ***@***.***>; Author ***@***.***>
Asunto: Re: [technyon/nuki_hub] Feature request (Issue #183)

 

What exactly is your use case. There a lot of things covered by the ble API, adding all of those in an MQTT API could prove difficult. Do you just want to enable/disable existing authorizations?

**Comment by technyon** [comment]
Hi,

Just enabling or disabling existing authorizations should be possible, but it's not a small feature request. I'll look into and and see what I can do.

**Comment by Eguar-rc** [comment]
Thanks, with that nuki_hub would cover everything that I previously did through the web.
Thank you also for sharing your work, I have applied it and it is working perfectly.
