### ISSUE TITLE
 GPIO legend

### ISSUE THREAD

**Issue by Asino123** [technyon/nuki_hub#184]
Good morning, thank you for your wonderful work. I previously configured a nuki_hub with version 6. I did several tests and one of the options I used and which I found essential was the opening and closing via GPIO. The functionality had been tested successfully. Now looking at the guide I can't find where the GPIOs are indicated for opening and closing. Could you help me? Thanks.

**Comment by technyon** [comment]
In the latest version, GPIO is configured by the user, you can select which PIN does what. Open the configuration portal and click Edit under "GPIO Configuration". Configure the PINs however you need them and click save. If you need a reference to the previous configuration, you can check the history of the README.md file on github.

**Comment by Asino123** [comment]
Thanks a lot for the answer.  i will update my version.

Il dom 30 apr 2023, 10:25 Jan-Ole Schümann ***@***.***> ha
scritto:

**Comment by technyon** [comment]
@Asino123 Did this resolve your issue?

**Comment by Asino123** [comment]
hi, yes thank you very much.

Il sab 6 mag 2023, 12:01 Jan-Ole Schümann ***@***.***> ha
scritto:

**Comment by technyon** [comment]
ok, closing issue
