### ISSUE TITLE
Unlach Help

### ISSUE THREAD

**Issue by CAVACO-PT** [technyon/nuki_hub#193]
Hi , thank you for the work on this , its realy better than the bridge ...

i have disconnected one of my locks from the bridge and pair with with a m5 atom POE , everyhing is working inside mqtt and HA , but i dont have any unlach options , its the one of the most used features i need , 

can someone point me out in the right direction to get this working , im been looking and dont see anything wrong 

![image](https://github.com/technyon/nuki_hub/assets/9946471/ba1a0662-dce1-4047-b824-465b982c9942)

**Comment by CAVACO-PT** [comment]
ok , seams the command is not present , but the service works 👍 

![image](https://github.com/technyon/nuki_hub/assets/9946471/2701f916-8a26-43c3-824e-ec131203bb8e)

**Comment by mundschenk-at** [comment]
It is, that is the HA standard way of effecting that action. You can always add helper button that calls the service if you want that specific UI.

**Comment by CAVACO-PT** [comment]
Anyone knows if this can handle mutiple locks ?? i had problems with the nuki bridge handling multiple locks , due to it being limited handling mutiple requests , can i add here my 2 locks without any issues ??

**Comment by mundschenk-at** [comment]
You need a separate ESP per lock.
