### ISSUE TITLE
Unreliability Issue

### ISSUE THREAD

**Issue by cpiccoli-polimi** [technyon/nuki_hub#196]
Hi, since like 2 weeks the NukiHUB has become really unreliable: i almost cannot use it.
When opening/closing the lock manually or via its app the status change is not recognized, when trying to open/close via HomeAssistant it does not work or maybe it will but after like 5 minutes waiting... the only way to solve it is to restart the ESP32 and immediately after open/close, but then it will be stuck for minutes/hours again.
How can i solve?

It was working well before, i am using Mosquitto on HomeAssistant, i did not change anything in the configuration of the network, HomeAssistant etc, i tried updating the firmware some days ago but it does not work the same, i tried working on configuration parameters (like rebooting on certain conditions) but still no success..

```
NUKI Hub version: 8.24
run: true
deviceId: #########
deviceIdOp: #########
mqttbroker: 192.168.1.51
mqttport: 1883
mqttuser: ***
mqttpass: ***
mqttlog: true
lockena: true
mqttpath: nuki
openerena: false
mqttoppath: 
maxkpad: 
opmaxkpad: 
mqttca: 
mqttcrt: 
mqttkey: 
hassdiscovery: homeassistant
dhcpena: false
ipaddr: 192.168.1.244
ipsub: 255.255.255.0
ipgtw: 192.168.1.254
dnssrv: 192.168.1.254
nwhw: 1
rssipb: 60
hostname: nukihub
nettmout: 30
restdisc: true
rstbcn: 60
lockStInterval: 60
configInterval: 3600
batInterval: 3600
kpInterval: 1800
kpEnabled: false
accLvl: 0
regAsApp: false
nrRetry: 3
rtryDelay: 100
crdusr: 
crdpass: 
pubauth: false
pubdbg: false
prdtimeout: -1
hasmac: false
macb0: 
macb1: 
macb2: 
MQTT connected: Yes
Lock firmware version: 3.6.9
Lock hardware version: 6.11
Lock paired: Yes
Lock PIN set: Yes
Lock has door sensor: No
Lock has keypad: No
Network device: Built-in Wifi
Uptime: 3 minutes
Heap: 89656
Stack watermarks: nw: ####, nuki: ###, pd: ###
Restart reason FW: GpioConfigurationUpdated
Restart reason ESP: ESP_RST_SW: Software reset via esp_restart.
```

**Comment by technyon** [comment]
Hi, it's unfortunately hard to say what's going wrong. Can you get logs, I think in your case it's best to get serial logs. Download for example "hterm", connect the ESP to a PC and connect to the ESP to get log output.

Btw. you've masked the stack watermarks which are an interesting data point. These show the amount of memory available for certain tasks, it's not private information in any way. Although not really that important, there's no need to mask the device Ids, they are just random numbers generated the first time the ESP boots up.

**Comment by cpuks** [comment]
Had same issues after installing 8.24 - hub becomes unavail after day-two sometimes few hours after reboot, reverting to 8.23 without any config change solved issue - 7 days now without problems.

**Comment by cpiccoli-polimi** [comment]
> Try this binary ... I've downgraded the Arduino core for ESP32 to the previous version.
> 
> [nuki_hub-core-2.0.8-1.zip](https://github.com/technyon/nuki_hub/files/11898130/nuki_hub-core-2.0.8-1.zip)

This seems to have solved the problems, at least in the past few days i've tried it.
I noticed it was also a matter of temperatures: using an heatsink on the ESP32 the downtimes were less frequent

**Comment by technyon** [comment]
Hi,

thanks for the feedback, we're doing some more test.

**Comment by technyon** [comment]
This is now officially in release 8.25
