### ISSUE TITLE
Support for simulating the door sensor

### ISSUE THREAD

**Issue by OnFreund** [technyon/nuki_hub#197]
Not sure if the Nuki BLE API supports that, but it would be great if the hub could simulate a door sensor that can be controlled via MQTT and GPIO (for example, the GPIO could be directly connected to a sensor, or HA could have a switch entity that can mirror the state of another door sensor).

That way a 3rd party door sensor can be used the same way that the Nuki sensor is used.

**Comment by technyon** [comment]
This is not possible unfortunately, there's no easy way to make the ESP behave like a door sensor. What you can do with the latest version of Nuki Hub is to use a GPIO as an input and connect a door sensor, howevery this will just report it to your home automation system, not the lock itself.

**Comment by OnFreund** [comment]
Thanks. The objective is to report to the lock itself so that it can act on it just like it does with the Nuki door sensor.
Looks like there's an open feature request, but it's not getting any love: https://developer.nuki.io/t/support-set-of-door-sensor-state-through-api-for-use-with-external-sensor/11694/3

**Comment by technyon** [comment]
Hi,

I'm closing this for now. I don't have high hopes for that feature request, but should it get accepted, we can open this issue again.
