### ISSUE TITLE
Pair App with Bridge (HUB)

### ISSUE THREAD

**Issue by wwwDESIGN-basti** [technyon/nuki_hub#204]
Hey Guys,

is there a way to pair the nuki app with the esp32 nuki hub, to extend the bluetooth range for the opener?
What should i do to do this?

**Comment by technyon** [comment]
Hi,

No this is not possible, NUKI Hub works independently of the app. In what way do you need to "extend the bluetooth range". Does your ESP have problems communicating with the opener? In that case you have to move the ESP closer to the opener.

**Comment by platini76** [comment]
I think he (as me) want to activate option: nuki web to lock and unlock nuki from app also out phone BT range

**Comment by technyon** [comment]
Hi,

Sorry for the late answer. The idea is to connect your NUKI device to your smarthome system (Home Assistant, iobroker, FHEM, OpenHAB, ...) via MQTT. The smarthome system then provides a web interface to control the device.
