### ISSUE TITLE
it is possible to add nuki_hub to esphome?

### ISSUE THREAD

**Issue by platini76** [technyon/nuki_hub#207]
sorry for noob question..

**Comment by technyon** [comment]
The short answer is no.

The longer answer is: NUKI Hub builds upon a library to communicate with NUKI devices (https://github.com/I-Connect/NukiBleEsp32). I think I've seen a project already that uses this library to add NUKI devices to esphome.

**Comment by platini76** [comment]
thanks
is this one?
https://github.com/uriyacovy/ESPHome_nuki_lock

**Comment by technyon** [comment]
Yes that should be the correct one.
