### ISSUE TITLE
Suggested sound_level payload (HA discovery topic) modification for nicer GUI setting

### ISSUE THREAD

**Issue by katiuskt** [technyon/nuki_hub#209]
By default, if "home assistant" discovery topic is enabled, the sound_level topic is shown like this (just a number):
![imagen](https://github.com/technyon/nuki_hub/assets/75622100/1bddd75c-c990-4189-8c6a-94b3b4e29912)

`homeassistant/sensor/ID/sound_level/config`
```
{
    "~": "nukiopener",
    "cmd_t": "~/configuration/soundLevel",
    "dev": {
        "ids": [
            "nuki_ID"
        ],
        "mdl": "Opener",
        "mf": "Nuki",
        "name": "Intercom"
    },
    "ent_cat": "config",
    "ic": "mdi:volume-source",
    "max": "255",
    "min": "0",
    "name": "Intercom Sound level",
    "stat_t": "~/configuration/soundLevel",
    "unique_id": "ID_sound_level"
}
```

My proposal is to move the topic from "sensor" to "number" (https://www.home-assistant.io/integrations/number.mqtt/) and include both "step" and "mode" variables like this:

`homeassistant/number/ID/sound_level/config`
```
{
    "~": "nukiopener",
    "cmd_t": "~/configuration/soundLevel",
    "dev": {
        "ids": [
            "nuki_ID"
        ],
        "mdl": "Opener",
        "mf": "Nuki",
        "name": "Intercom"
    },
    "ent_cat": "config",
    "ic": "mdi:volume-source",
    "max": "255",
    "min": "0",
    "mode": "slider",
    "step": "50",
    "name": "Intercom Sound level",
    "stat_t": "~/configuration/soundLevel",
    "unique_id": "ID_sound_level"
}
```

This way, the outcome in Home Assistant will look nicer with an slider (similarly to the way the volume is set into nuki's app):
![imagen](https://github.com/technyon/nuki_hub/assets/75622100/bd1844a5-37aa-4e33-bcc6-434d294b1153)

**Comment by technyon** [comment]
I'll look into it when I find the time.
