### ISSUE TITLE
Ability to configure lock/unlock mqtt actions

### ISSUE THREAD

**Issue by JesusRo** [technyon/nuki_hub#212]
Hi,

When calling unlock service on homeassistant (mqtt integration), it enables RTO which cannot be configured longer than 60m.
It automatically "locks" after that time.

I´ve modified the definition at homeassistant/lock/id/smartlock/config
```
{
  "dev": {
    "ids": [
      "nuki_ID"
    ],
    "mf": "Nuki",
    "mdl": "Opener",
    "name": "NukiOpener"
  },
  "~": "nukiopener",
  "name": "NukiOpener",
  "unique_id": "2c181e9a_lock",
  "cmd_t": "~/lock/action",
-   "pl_lock": "deactivateRTO",
-   "pl_unlk": "activateRTO",
+   "pl_lock": "deactivateCM",
+   "pl_unlk": "activateCM",
  "pl_open": "electricStrikeActuation",
  "stat_t": "~/lock/binaryState",
  "stat_locked": "locked",
  "stat_unlocked": "unlocked",
  "opt": "false"
}
```
To enable/disable ContinuousMode which has no timeout.
Working fine so far.

Could be possible to configure this behaviour via web interface?

Thanks in advance.

**Comment by technyon** [comment]
Hi,

It should be possible to make this configurable, I'll look into it.
