### ISSUE TITLE
Manual unlock/lock not reporting

### ISSUE THREAD

**Issue by deangreen4** [technyon/nuki_hub#218]
Hi,
am running version 8.25 of nuki bridge with an ultion lock which uses the nuki 3.0. All is well if the lock is unlocked with the nuki app, clicking the button or using home assistant but if you just turn the knob on the nuki, or use a key from the outside, this does not cause a state change on the bridge. The nuki app shows this state change. Any ideas?

Thanks

**Comment by technyon** [comment]
I don't have too much information about that lock, but once a state change happens, it should signal it via a flag in the ble beacons. My guess would be that for some reason it doesn't set that flag.

**Comment by deangreen4** [comment]
Oddly, without me doing anything else - its started working perfectly!
Thanks for all your hard work on this code
