### ISSUE TITLE
MQTT greyed out.

### ISSUE THREAD

**Issue by dan-lindley** [technyon/nuki_hub#219]
I've managed to get the esp32 flashed. I can see the hub on WiFi via it's IP. It's showing lock status etc (and BLE address).

MQTT in home assistant is blank with all unknown statuses. I've done something wrong somewhere but I have no idea where! If anyone can guide me to get it configured I would be grateful.

Thank you

Dan
![Screenshot_20230807-100322](https://github.com/technyon/nuki_hub/assets/96248288/07cf8ee5-4943-4693-8034-9cdf95b1df3a)

**Comment by technyon** [comment]
Please post the content of the system information page.

**Comment by technyon** [comment]
Closed due to inactivity
