### ISSUE TITLE
MQTT naming changes in HA

### ISSUE THREAD

**Issue by nelsongraca** [technyon/nuki_hub#220]
Updated my HA and now it's complaining about changes in MQTT entities pointing to the following page: https://developers.home-assistant.io/blog/2023-057-21-change-naming-mqtt-entities/

**Comment by Arn0uDz** [comment]
Already reported.

[#217](https://github.com/technyon/nuki_hub/issues/217)

**Comment by nelsongraca** [comment]
@Arn0uDz I missed it, closing this one
