### ISSUE TITLE
Esp32 is not re-connecting if the connection was dropped

### ISSUE THREAD

**Issue by avidavidov** [technyon/nuki_hub#228]
Hi, I am using the 8.26 version.
I have noticed that when I reboot my router the esp module is unable to communicate with the lock.
Only after I reset the esp its working again.
Is there some configuration I missed that can help with handling this case?
Thanks

**Comment by technyon** [comment]
Try enabling "Restart on disconnect" if you haven't done so already.

**Comment by avidavidov** [comment]
Yeah, looks like this configuration solves my problem. Totally missed that.
