### ISSUE TITLE
 The unlatch function does not appear anywhere.

### ISSUE THREAD

**Issue by a9965** [technyon/nuki_hub#231]
Where can I find the unlatch function?

**Comment by mundschenk-at** [comment]
If you mean in Home Assistant, it is `lock.open`.

**Comment by a9965** [comment]
I do not know what you mean. My entity is called "entrada" and I have tried what you mentioned but it doesn't work.

**Comment by mundschenk-at** [comment]
The service to call is named `lock.open` (with your specific `lock` entity as the target).

**Comment by a9965** [comment]
Is the code I showed you above what you mean? If not, I don't know how to do it. Thank you.

**Comment by mundschenk-at** [comment]
This looks like part of a dashboard configuration, I don't know what exactly your are trying to do there. I suggest you test your service calls through the Developer Tools.

**Comment by SergioWarriorPeru** [comment]
> Is the code I showed you above what you mean? If not, I don't know how to do it. Thank you.

I use node red and I have configured in this way
![ESP32](https://github.com/technyon/nuki_hub/assets/77809496/5e12584f-b9a3-4a89-b5fd-8d07b6517905)

**Comment by iranl** [comment]
An auto discovered Unlatch button for Home Assistant was added in #285 en will be part of the next release. 

Should also close this issue.

**Comment by technyon** [comment]
Correct. Closing please wait for the next release.
