### ISSUE TITLE
Mqtt Code not working

### ISSUE THREAD

**Issue by MrJamsn** [technyon/nuki_hub#238]
Hi, I am not sure if this is an issue of mqtt or nukihub. 
but I tried to set a code via the default_code field in Mqtt device setting. Though, code is not asked before execution. I also tried to change my nuki pin, no difference
any Idea? 
![IMG_3482](https://github.com/technyon/nuki_hub/assets/39996788/4347026c-5f59-4e49-876b-723d8d7dd54e)
Thanks! Great Development!! Love it so far :)

**Comment by MrJamsn** [comment]
NUKI Hub version: 8.27
run: true
deviceId: 534405045
deviceIdOp: 534405045
mqttbroker: 192.168.178.41
mqttport: 1883
mqttuser: ***
mqttpass: ***
mqttlog: true
lockena: true
mqttpath: nuki
openerena: false
mqttoppath: 
maxkpad: 
opmaxkpad: 
mqttca: 
mqttcrt: 
mqttkey: 
hassdiscovery: homeassistant
dhcpena: true
ipaddr: 
ipsub: 
ipgtw: 
dnssrv: 
nwhw: 1
rssipb: 60
hostname: nukibridge
nettmout: 60
restdisc: true
rstbcn: 60
lockStInterval: 1800
configInterval: 3600
batInterval: 1800
kpInterval: 1800
kpEnabled: false
accLvl: 0
regAsApp: false
nrRetry: 0
rtryDelay: 100
crdusr: 
crdpass: 
pubauth: false
pubdbg: false
prdtimeout: 60
hasmac: false
macb0: 
macb1: 
macb2: 
MQTT connected: Yes
Lock firmware version: 3.6.9
Lock hardware version: 6.11
Lock paired: Yes
Lock PIN set: Yes
Lock has door sensor: No
Lock has keypad: No
Network device: Built-in Wifi
Uptime: 14 minutesHere we go :)____________Am 18.10.2023 um 18:22 schrieb Jan-Ole Schümann ***@***.***>:﻿
Please post the content of the system information page (click on the firmware version)

**Comment by technyon** [comment]
MQTT is connected. I'm not sure what default code is about, but if you want to configure the PIN, set it in the NUKI Hub configuration portal.

**Comment by alexdelprete** [comment]
> but I tried to set a code via the default_code field in Mqtt device setting. Though, code is not asked before execution.

where did you read that field is for setting a code that will be asked when calling lock/unlock/open? or it was simply an assumption? :)

**Comment by MrJamsn** [comment]
I assumed based on this Article :)Lock Entity | Home Assistant Developer Docsdevelopers.home-assistant.io___Am 19.10.2023 um 17:32 schrieb Alessandro Del Prete ***@***.***>:﻿

but I tried to set a code via the default_code field in Mqtt device setting. Though, code is not asked before execution.

where did you read that field is for setting a code that will be asked when calling lock/unlock/open? or it was simply an assumption? :)

**Comment by MrJamsn** [comment]
Okay. That‘s why I am asking :)Thought its software only, like how the mqtt lock identifies itselfs. Not a code wanted by the lock :)BRAm 19.10.2023 um 19:44 schrieb Alessandro Del Prete ***@***.***>:﻿

I assumed based on this Article :) https://developers.home-assistant.io/docs/core/entity/lock/

"Some Locks"

**Comment by alexdelprete** [comment]
> That‘s why I am asking :)

And that's why I'm answering. :)
