### ISSUE TITLE
Support for multiple Nuki Locks?

### ISSUE THREAD

**Issue by turbolooser** [technyon/nuki_hub#239]
Just found this great project.
Wondering If I could connect 2 Nuki Locks to 1 nuki-hub?

How to troubleshoot the pairing if its not doing anything?

**Comment by smobils** [comment]
1 lock = 1 hub , if you need to use 2 locks you will need 2 hubs 

On 20 Oct 2023, at 05:40, turbolooser ***@***.***> wrote:﻿
Just found this great project.
Wondering If I could connect 2 Nuki Locks to 1 nuki-hub?
How to troubleshoot the pairing if its not doing anything?

**Comment by technyon** [comment]
Hi,

If you have two locks you'll need two ESPs.
