### ISSUE TITLE
Control multiple locks using MQTT

### ISSUE THREAD

**Issue by jongoikolea** [technyon/nuki_hub#240]
Hi, I'm writing a script to control multiple locks via MQTT, but every ESP32 nuki_hub device seems to be subscribed to the same topics (nuki/#), so I can't control them individually. Is there an easy workaround for this?
Thanks.

**Comment by mundschenk-at** [comment]
Change the topic prefix under `NUKI Configuration` (it's called `MQTT NUKI Smartlock Path`).

**Comment by jongoikolea** [comment]
Thanks a lot! It was as simple as that.
