### ISSUE TITLE
Confusing or erroneous GPIO lock control documentation

### ISSUE THREAD

**Issue by jongoikolea** [technyon/nuki_hub#241]
Hi,

I was conducting some MQTT tests and noticed a discrepancy in the GPIO lock control (optional) section of the readme file regarding the paths to access the GPIO pins:

"General input (pull-up): The pin is configured in pull-up configuration and its state is published to the **"gpio/pin_x/state"** topic
Genral output: The pin is set to high or low depending on the **"gpio/pin/x/state"** topic"

However, I was only able to get it working using the "gpio/pin_x/state" format. Is this a documentation error?

**Comment by technyon** [comment]
I'll check it, probably a copy/paste mistake.

**Comment by technyon** [comment]
readme updated
