### ISSUE TITLE
Help controlling GPIO output in Home Assistant

### ISSUE THREAD

**Issue by asmaran85** [technyon/nuki_hub#247]
I connected a relay to pin P21 of the ESP32 on which NukiHub runs.
GPIO configuration -> GPIO 21 -> general output
In the configuration.yaml file I added the lines: 

`mqtt:
   switch:
    - unique_id: suoneria_citofono
      name: "Suoneria citofono"
      command_topic: "gpio/pin_21/state"
      payload_on: "1"
      payload_off: "0"`

In Home Assistant I see the new switch but I can't control it.
I'm not very good at mqtt. I tried with different payload (on/off, 1/0, high/low)
I tried also "command_topic: "nuki/gpio/pin_21/state""

Thanks

**Comment by technyon** [comment]
"nuki/gpio/pin_21/state" should be correct, unless you changed the MQTT path for the lock. Write "0" or "1" into this topic ... if that doesn't work, use an MQTT Client like MQTT explorer and monitor what happens on that topic if you toggle the switch.

**Comment by asmaran85** [comment]
Is this good:
---------
mqtt:
  switch:
    - unique_id: suoneria_citofono
      name: "Suoneria citofono"
      command_topic: "nuki/gpio/pin_21/state"
      state_topic: "nuki/gpio/pin_21/state"
      payload_on: "1"
      payload_off: "0"
-----------

**Comment by asmaran85** [comment]
it doesn'work

**Comment by asmaran85** [comment]
Using the switch on home assistant the state changes right on mqtt explorer
![image](https://github.com/technyon/nuki_hub/assets/95779207/eebad204-6732-461b-bcea-25948ef05838)

But nothing happened on the relay (I moved it on pin23)

**Comment by technyon** [comment]
It all looks correct. Could you get logs while switching the GPIO? You can use HTERM and connect the ESP to your PC, then look at the output while switching. Baud rate is 115200, you should line break to CR+LF.

**Comment by asmaran85** [comment]
I changed the relay using a 2-relays-board and everything works!
Thank you very much!

**Comment by technyon** [comment]
ok, glad it works now
