### ISSUE TITLE
FYI: ESP32-S3 can work

### ISSUE THREAD

**Issue by bobobo1618** [technyon/nuki_hub#249]
Just thought you might be interested to know that I got this working on an Adafruit ESP32-S3 Feather (No PSRAM). I had to change the desired board in `BoardOptions.cmake` and select the relevant board when I ran CMake. I also manually copied the bootloader bin but I'm not sure if that was necessary.

Feel free to close, this is just informational.

**Comment by technyon** [comment]
Hi,

Thanks. Let's continue discussion in the already existing issue #201
