### ISSUE TITLE
Feature: Catch Keypad Input

### ISSUE THREAD

**Issue by janoschbatschi** [technyon/nuki_hub#250]
Hey, 

thank you for your great work! I was just wondering if it's possible to get the entered PINs to HA or at least the name of the corresponding PIN? 

The idea is to use the entered PIN as an event to open multiple doors. Like PIN1 for garage and PIN2 for entry door.

**Comment by technyon** [comment]
Hi,

No this is not possible, neither the numbers nor the PIN entered is exposed by the API.

**Comment by janoschbatschi** [comment]
Thank you for your fast answer!
