### ISSUE TITLE
Improvements in state of the lock 

### ISSUE THREAD

**Issue by Mikescotland** [technyon/nuki_hub#253]
Hello
Using with version 3.0 non pro. Tested with HA other integration over Bluetooth and
1. Is it possible to integrate intermediate states like "locking" or "unlocking"? Now it's only reporting locked / unlocked.
2. Nuki Hub sometimes takes 8 seconds for the status to be updated. Any way of shortening it? Seems like nuki app somehow faster communicates with the lock.

**Comment by technyon** [comment]
1. It is implemented already, but often missed because those states are only active for a short time.
2. Can you get serial logs. You can use for example HTERM to connect to the ESP, baud rate is 115200.
