### ISSUE TITLE
Gpio input Unlatch, false triggering.

### ISSUE THREAD

**Issue by mrbluebrett** [technyon/nuki_hub#256]
Hi, I have nuki-hub 8.27 installed on a esp32. I have connected another esp to gpio 17 and selected mode “Input unlatch”. When i try to unlatch the door from the other esp works fine, however I’m getting random unlatches. Even if I disconnect the cable from the other esp I’m still getting random unlatches.
What can it be? 
I see in the code that Input Pullup is enabled, so adding another pull up resistor won’t help right? 
What else can I try?

**Comment by mrbluebrett** [comment]
It’s another esp8266 with a gpio switch configured to connect to ground. This part works fine.
The cable betwen the esps is maybe 10cm.
And there are other electrical cables, is a box with cables and a zigbee switc module. 
My guess is some kind of interference. I have detected that when i turn on the light of the zigbee module it trigger the unlatch.
How can i filter this interferences?

**Comment by technyon** [comment]
Do both the ESP32 and the ESP8266 share same ground ... are they powered by the same power source? If not that could be a problem already.

You can:
- Reduce the cable length if possible
- Move the ESPs further away from the rest of the electronics

Actual shielding would mean putting the ESPs into a grounded metal cage I guess, probably not the easiest thing to do.

**Comment by mrbluebrett** [comment]
Do you have the debounce option enabled for gpios?
Also I will try a capacitor of 0.1uF between the GPIO and ground when i have some time.

**Comment by technyon** [comment]
There's no debounce needed because there's a long delay after an action is triggered. And even if it's triggered twice, you'd just retriggering the current action again.

**Comment by mrbluebrett** [comment]
I thought debounce was used to avoid this kind of spikes…

**Comment by mrbluebrett** [comment]
No luck with capacitor of 0.1uF

**Comment by technyon** [comment]
I'm not an electronics expert unfortunately :).

Maybe adding a grounded metal plate between the ESPs and rest could do the trick, it did once in another project of mine. Maybe try with cardboard and aluminum foil first.

**Comment by technyon** [comment]
Did you have any luck fixing this?

**Comment by mrbluebrett** [comment]
No… i tried everything i could think of with no luck. I finally removed the nukihub firmware and used the esp32 with esphome, unifying both devices in one, using the nuki lock comoonent in esphome. The component it’s no as reliable as this nukihub, but at least it only unlatches the door when it should.

**Comment by technyon** [comment]
So this means it's not a hardware problem. I'd really to know what esphome does differently to not have false positives. Nuki hub is interrupt triggered, so as soon as it gets the signal, it'll execute the action. Maybe esphome has some more checks to make sure the signal is stable for a certain time.

**Comment by mrbluebrett** [comment]
No, no, there’s no cable conected now. I had 2 esps (1 for nukihub an another for the fingerprint sensor with esphome). Now i have only one, everything in esphome. So no gpio input triggering.
The only downside is that it’s not so reliable (it loses connection once in a while, or when sending command it loses connection for 5-10 seconds) and it’s not actively developed or mbtained by the repo owner anymore.

**Comment by technyon** [comment]
Ok that makes more sense :).

You could actually have two ESPs, but instead of connecting them with a wire you trigger NUKI Hub over MQTT.

**Comment by technyon** [comment]
ok, I understand your point. Since there's not much more I can do to help, I'd close the issue for now
