### ISSUE TITLE
Nuki Opener: lock/state changing between ring and locked in seconds 

### ISSUE THREAD

**Issue by MarcAroni81** [technyon/nuki_hub#264]
Hello,

I have paired the Nuki Opner to the Nuki Hub v 8.28 (mqtt nuki opener path set to: "nukiopener")
Now I receive in seconds intervall the mqtt "nukiopener/lock/state" = "locked" and "ring" which ends up flickering the "ring detected" MQTT sensor. 

Any ideas where to start debugging this behavior? 

What I already did with no impact on the issue:
- flashed the ESP32 device and re-installed nuki_hub
- restarted HA as well as nuki_hub several times
- removed the MQTT device and waited for it to be discovered again
- removed the Nuki Opener from the hub!! 

Many thanks for your help!
Marcus

**Comment by MarcAroni81** [comment]
I fixed it myself:

I disconnected the Nuki Opener from the Hub,
resetted Nuki Opener Device (Factory Reset) and did the initial setup 
re-paired the device 

= 
fixed

**Comment by technyon** [comment]
Glad you could fix it. I had a similar issue some time ago that could only be fixed by a factory reset.
