### ISSUE TITLE
feature request: OTA Updates & Update info

### ISSUE THREAD

**Issue by miggi92** [technyon/nuki_hub#269]
It would be nice to have a OTA Update Button and an Information if there is a new update available.

Example:
![image](https://github.com/technyon/nuki_hub/assets/9019692/6c2b1bbc-d0be-49b1-b527-f0b30c7387c2)

Update Button:
![image](https://github.com/technyon/nuki_hub/assets/9019692/be808231-6c72-493e-a0df-2e4d900fa238)

Doesn't have to be done in the way of the example pictures.

**Comment by technyon** [comment]
See issue #125

**Comment by miggi92** [comment]
> See issue #125

ah thanks. Sry didn't see that issue.

**Comment by iranl** [comment]
#293 should partially fix this as it will enable automatic update checks that show the latest release in the web interface, MQTT and Home Assistant.

I don't believe true (semi)automatic updating that will download and install the latest binary is feasable at this time.

Propose merging #293 will close this for the time being.

**Comment by iranl** [comment]
@technyon @miggi92 Can this be closed with the modifications in the latest release?

**Comment by miggi92** [comment]
@iranl  yes. I'll close it.
