### ISSUE TITLE
Add battery percentage sensor to Home Assistant

### ISSUE THREAD

**Issue by mundschenk-at** [technyon/nuki_hub#27]
It would be nice if a battery percentage sensor could be added to HA (in addition to existing the "low battery" binary sensor).

**Comment by MattDog06** [comment]
In general a better MQTT auto. discovery for Home Assistant would be nice. I have created some payloads and added them manually. It would be nice if someone could add them to the source: [Front Door Lock.zip](https://github.com/technyon/nuki_hub/files/9290062/Front.Door.Lock.zip)
.

**Comment by technyon** [comment]
I'll have a look at it.

**Comment by technyon** [comment]
Please check the latest release
