### ISSUE TITLE
Trouble with 2nd NukiHub

### ISSUE THREAD

**Issue by mkomarac** [technyon/nuki_hub#275]
Hello.
First of all, I woud like to say that this is a great project, and a lot of effort put into it.
Couple a weeks ago, I have had one esp32 laying around, and implemented into HASS seamlessly.
Four days ago finally arrived 2nd esp32, and I wanted to add it to my 2nd Nuki lock.
renamed as noted, and all of data coming into MQTT broker.
but device never showed up in mqtt integration in home assistant as device. Restarted, rebooted HASS, but no luck
I have tried with multiple ESP's but 2nd is never discovered by mqtt integration.
Have I missed something?

If I put nuki name as default, the device showed up, but controlling 2 locks as one, what's not an option.

thanks in advance

**Comment by alexdelprete** [comment]
If the correct entities are created in MQTT, the device has to show up in HA. So please check the MQTT broker, and post a screenshot of the topics of the second lock.

**Comment by technyon** [comment]
Also post the contents of your the system information pages of your ESPs (click on the firmware version)

**Comment by mkomarac** [comment]
Here are more details:
Both of hubs are connecting to each lock, and read states
NukiHub that is discoverable by HomeAssistant is FW v.8.28, and other one 8.29
![image](https://github.com/technyon/nuki_hub/assets/37035814/52930625-fa8e-4365-8da7-53e015a27298)
2nd Hub path is changed as noted
![image](https://github.com/technyon/nuki_hub/assets/37035814/be248dcf-eaf5-4fb0-983e-0d2acd8807ae)
MQTT Topic
![image](https://github.com/technyon/nuki_hub/assets/37035814/9b97957d-d6eb-4e21-aff4-f6f5f7108194)

MQTT Explorer
![image](https://github.com/technyon/nuki_hub/assets/37035814/186d1708-a07c-4886-88dc-1b1883f8022c)
![image](https://github.com/technyon/nuki_hub/assets/37035814/5804747e-b33e-45eb-8e58-2fff0813ebdf)

Under homeassistant path
![image](https://github.com/technyon/nuki_hub/assets/37035814/fa625307-ba95-475f-8452-e2a77bbba5b3)

and in Home Assistant there is only one nuki
![image](https://github.com/technyon/nuki_hub/assets/37035814/f8bc896b-5924-4a22-9578-1de8c2a4b03f)

![image](https://github.com/technyon/nuki_hub/assets/37035814/a9615dba-415e-4986-80dc-98013b856ac1)
![image](https://github.com/technyon/nuki_hub/assets/37035814/941be2ba-87d6-4126-8025-ba3044938faa)

if any more information is needed, just ask

thanks

**Comment by mkomarac** [comment]
System Information
NUKI Hub version: 8.28
run: true
deviceId: 3163309255
deviceIdOp: 3163309255
mqttbroker: 10.10.10.10
mqttport: 1883
mqttuser: ***
mqttpass: ***
mqttlog: false
lockena: true
mqttpath: nuki
openerena: false
mqttoppath: 
maxkpad: 
opmaxkpad: 
mqttca: 
mqttcrt: 
mqttkey: 
hassdiscovery: homeassistant/KitchenDoor
dhcpena: true
ipaddr: 
ipsub: 
ipgtw: 
dnssrv: 
nwhw: 1
rssipb: 60
hostname: nukihub1
nettmout: -1
restdisc: false
rstbcn: -1
lockStInterval: 1800
configInterval: 3600
batInterval: 1800
kpInterval: 1800
kpEnabled: false
accLvl: 0
regAsApp: false
nrRetry: 0
rtryDelay: 100
crdusr: 
crdpass: 
pubauth: false
pubdbg: false
prdtimeout: 60
hasmac: false
macb0: 
macb1: 
macb2: 
MQTT connected: Yes
Lock firmware version: 4.0.36
Lock hardware version: 8.3
Lock paired: Yes
Lock PIN set: No
Lock has door sensor: No
Lock has keypad: No
Network device: Built-in Wifi
Uptime: 105 minutes
Heap: 90432
Stack watermarks: nw: 6104, nuki: 664, pd: 236
Restart reason FW: RequestedViaMqtt
Restart reason ESP: ESP_RST_SW: Software reset via esp_restart.

System Information
NUKI Hub version: 8.29
run: true
deviceId: 223456177
deviceIdOp: 223456177
mqttbroker: 10.10.10.10
mqttport: 1883
mqttuser: ***
mqttpass: ***
mqttlog: false
lockena: true
mqttpath: main
openerena: false
mqttoppath: 
maxkpad: 
opmaxkpad: 
mqttca: 
mqttcrt: 
mqttkey: 
hassdiscovery: homeassistant/FrontDoor
dhcpena: true
ipaddr: 
ipsub: 
ipgtw: 
dnssrv: 
nwhw: 1
rssipb: 60
hostname: nukihub11
nettmout: -1
restdisc: false
rstbcn: -1
lockStInterval: 1800
configInterval: 3600
batInterval: 1800
kpInterval: 1800
kpEnabled: false
accLvl: 0
regAsApp: false
nrRetry: 0
rtryDelay: 100
crdusr: 
crdpass: 
pubauth: false
pubdbg: false
prdtimeout: 60
hasmac: false
macb0: 
macb1: 
macb2: 
MQTT connected: Yes
Lock firmware version: 4.0.36
Lock hardware version: 8.3
Lock paired: Yes
Lock PIN set: No
Lock has door sensor: No
Lock has keypad: No
Network device: Built-in Wifi
Uptime: 146 minutes
Heap: 91060
Stack watermarks: nw: 6104, nuki: 664, pd: 232
Restart reason FW: NotApplicable
Restart reason ESP: ESP_RST_INT_WDT: Reset (software or hardware) due to interrupt watchdog

**Comment by alexdelprete** [comment]
> Here are more details:
> Both of hubs are connecting to each lock, and read states
> NukiHub that is discoverable by HomeAssistant is FW v.8.28, and other one 8.29

![image](https://github.com/technyon/nuki_hub/assets/7027842/bf4afdde-4fff-4cb4-be20-ee56a3226789)

This is wrong configuration: you need to specify the main HA topic, not the subtopic. None of the hubs should be discoverable by HA with this configuration.

HA main topic has the entity types under it...

![image](https://github.com/technyon/nuki_hub/assets/7027842/1ab4d896-2746-4a6b-8743-794a6fc19782)

And under the lock entity subtopic you have the Nuki Hubs:

![image](https://github.com/technyon/nuki_hub/assets/7027842/83f6b72c-df53-42c2-8212-563756b3a67c)

That is your problem, you can easily fix it.

@technyon doc and description on the homeassistant config field should be more clear about this. I would call that "Home Assistant root audotiscovery topic". And in the docs I would specify it's the root, and 99.99999% it's not to be changed.

**Comment by technyon** [comment]
OK, let's update the documentation

**Comment by alexdelprete** [comment]
> OK, let's update the documentation

If you can give me access just to the documentation section, I can update it.

Or, I was thinking: can you enable the wiki? We could create a sort of FAQ.

**Comment by mkomarac** [comment]
> > Here are more details:
> > Both of hubs are connecting to each lock, and read states
> > NukiHub that is discoverable by HomeAssistant is FW v.8.28, and other one 8.29
> 
> ![image](https://private-user-images.githubusercontent.com/7027842/299656588-bf4afdde-4fff-4cb4-be20-ee56a3226789.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxODU5NDksIm5iZiI6MTcwNjE4NTY0OSwicGF0aCI6Ii83MDI3ODQyLzI5OTY1NjU4OC1iZjRhZmRkZS00ZmZmLTRjYjQtYmUyMC1lZTU2YTMyMjY3ODkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjVUMTIyNzI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTAzNWFlODZlZDM0YTkzYzM2ZDA1OGYwMzBjMGE0ZDFkNDc1ZWYxYjVjMjE1MjBiMDJlMjAzOWRjNTk1MjlmMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.n0DVncJ-TWxg6fQq7lkj7H1yeSFaV8oEZ2htNGMKAQU)
> 
> This is wrong configuration: you need to specify the main HA topic, not the subtopic. None of the hubs should be discoverable by HA with this configuration.
> 
> HA main topic has the entity types under it...
> 
> ![image](https://private-user-images.githubusercontent.com/7027842/299656854-1ab4d896-2746-4a6b-8743-794a6fc19782.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxODU5NDksIm5iZiI6MTcwNjE4NTY0OSwicGF0aCI6Ii83MDI3ODQyLzI5OTY1Njg1NC0xYWI0ZDg5Ni0yNzQ2LTRhNmItODc0My03OTRhNmZjMTk3ODIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjVUMTIyNzI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjM4Y2VkMzBhY2Q4YWU2MmJiM2FhNzRkZWI2MTFjMzFmOWYwNTY5ZWQ3YWM4NDFkNzM5MDBiNDBkM2IyMTRmNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.QQP_31rSFAuPUyNiTpW-nPgVTAbGboFwLzIHdrcBcus)
> 
> And under the lock entity subtopic you have the Nuki Hubs:
> 
> ![image](https://private-user-images.githubusercontent.com/7027842/299657226-83f6b72c-df53-42c2-8212-563756b3a67c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxODU5NDksIm5iZiI6MTcwNjE4NTY0OSwicGF0aCI6Ii83MDI3ODQyLzI5OTY1NzIyNi04M2Y2YjcyYy1kZjUzLTQyYzItODIxMi01NjM3NTZiM2E2N2MucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjVUMTIyNzI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGNlNjI4ZGM4YzJjYzI5MzY4ODFlN2Y5YTAyNTY4OTliOTBkM2ZjNGYyNGY3OTI3OTJkOWJhYzMyMDU0NjRlYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.TKQDMxwS0cwN-IW9cIRCLqHzyDOsIjlDuxSbzFJNkSA)
> 
> That is your problem, you can easily fix it.
> 
> @technyon doc and description on the homeassistant config field should be more clear about this. I would call that "Home Assistant root audotiscovery topic". And in the docs I would specify it's the root, and 99.99999% it's not to be changed.

Yes Sir.
That's the one!
Two NukiHubs in my Home Assistant
Thank You

**Comment by alexdelprete** [comment]
> Yes Sir.
> That's the one!
> Two NukiHubs in my Home Assistant
> Thank You

Glad it's working now. :)

Can you please close the issue? Thanks.

**Comment by technyon** [comment]
@alexdelprete I would give you access no problem, but that's unfortunately not possible with a free github account. You'll have to create a PR unfortunately.

**Comment by alexdelprete** [comment]
> @alexdelprete I would give you access no problem, but that's unfortunately not possible with a free github account. You'll have to create a PR unfortunately.

I have repos with other contributors that have free accounts. Are you sure about that?

**Comment by mundschenk-at** [comment]
Yeah, it should be possible to add collaborators in the repository settings: https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-access-to-your-personal-repositories/inviting-collaborators-to-a-personal-repository

**Comment by technyon** [comment]
ok then I just couldn't figure it out last time :D.

I've invited the two of you.

**Comment by alexdelprete** [comment]
> I've invited the two of you.

Make sure we don't break things accidentally!! I'll limit myself to edit docs/wiki. :D

**Comment by technyon** [comment]
With great power comes great responsibility :D.

I trust you not to break things.

**Comment by alexdelprete** [comment]
> I trust you not to break things.

And I trust you have local backups. :)

**Comment by technyon** [comment]
Git does have history.
