### ISSUE TITLE
Keypad Back Key

### ISSUE THREAD

**Issue by filou01** [technyon/nuki_hub#276]
Hi, i have the Nuki Pro 4.0 connected with MQTT directly vis Wifi and want to switch to Nuki Hub to save battery on my nuki. 
The only thing i can‘t configure in Home Assistant is to trigger a event in Home Assistant when the „Back Key“ is pressed in the keypad. 
With Wifi and MQTT on the pro i can catch this event. Is there any similar Topic or payload in this project where i can identify when the „Back Key“ was pressed?
Thank you and regards,
Christoph

**Comment by technyon** [comment]
Unfortunately no, there's no such functionality in the bluetooth API, which NUKI Hub uses to communicate with the lock
