### ISSUE TITLE
[Feature request] Add configuration_url to homeassistant autodiscovery 

### ISSUE THREAD

**Issue by mallorca2288** [technyon/nuki_hub#277]
Hello, first of all thank you for this great piece of software.

I was wondering if it would be possible to add the "configuration_url" key to the mqtt autodiscovery  for homeassistant. This is a very small improvement but very convenient to have. 

Maybe you could also consider adding the "sw_version" key even though we can already see this parameter with the Nuki Hub version sensor created in diagnostics.

For example:
```
{
  "dev": {
    "ids": [
      "nuki_3a7d95ec"
    ],
    "mf": "Nuki",
    "mdl": "SmartLock",
    "name": "Puerta casa",
    "configuration_url": "http://192.168.8.56",
    "sw_version": "Nuki HUB 8.30"
  },
  "~": "nuki",
  "name": null,
  "unique_id": "3a7d95ec_lock",
  "cmd_t": "~/lock/action",
  "avty": {
    "t": "~/maintenance/mqttConnectionState"
  },
  "pl_lock": "lock",
  "pl_unlk": "unlock",
  "pl_open": "unlatch",
  "stat_t": "~/lock/binaryState",
  "stat_locked": "locked",
  "stat_unlocked": "unlocked",
  "opt": "false"
}
```

This will create a link in the device page of homeassistant to open the configuration.

![imagen](https://github.com/technyon/nuki_hub/assets/16177130/754a2766-ab16-40d2-a7ae-c9607f69c01a)

Thanks in advance!

**Comment by technyon** [comment]
I think that should be possible
