### ISSUE TITLE
current cmake arduino toolchain blocks esp32-idf >= 2.0.10

### ISSUE THREAD

**Issue by zaolin** [technyon/nuki_hub#281]
Hi folks,

I finally compiled the project from scratch myself without using the VM.
Would you be interested in accepting fixes for the cmake Arduino project?

I can finally help with build instructions and fix the CMake stuff for idf 2.0.14. :)

**Comment by technyon** [comment]
Of course, go ahead and share.

**Comment by technyon** [comment]
Hi,

So I've tried building with 2.0.14 too, my only problem was that "file_opts" was missng. "touch file_opts" fixed the problem for me, but of course it would be better to fix this at cmake level. Do you have a solution already?

**Comment by zaolin** [comment]
Hey, I can try to push my stuff by the weekend. I also wanted to add some docs.
