### ISSUE TITLE
WiFi Connectivity issues

### ISSUE THREAD

**Issue by Rubeast** [technyon/nuki_hub#286]
I'm having connectivity issues with my NUKI Hub.
It would start by missing some pings and eventually completely dropping the connection.

Now I have enabled these option that I saw being recommended in an other topic.
"Restart if bluetooth beacons not received" to 60 seconds
"Restart on disconnect".

Since I made this change (30min ago), I have a constant ping open to the NUKI Hub and the connection dropped 2 times, but came back online this time. So the restart option seems to help.
Here you can see the pings that go missing:

> Reply from 192.168.4.3: bytes=32 time=51ms TTL=254
> Reply from 192.168.4.3: bytes=32 time=165ms TTL=254
> Reply from 192.168.4.3: bytes=32 time=303ms TTL=254
> Reply from 192.168.4.3: bytes=32 time=90ms TTL=254
> Reply from 192.168.4.3: bytes=32 time=100ms TTL=254
> Request timed out.
> Request timed out.
> Request timed out.
> Request timed out.
> Request timed out.
> Request timed out.
> Request timed out.
> Request timed out.
> Request timed out.
> Request timed out.
> Request timed out.
> Reply from 192.168.4.3: bytes=32 time=177ms TTL=254
> Reply from 192.168.4.3: bytes=32 time=216ms TTL=254
> Reply from 192.168.4.3: bytes=32 time=101ms TTL=254

When this happens I see this happing via the console window:

> Attempting MQTT connection
> MQTT: Connecting without credentials
> MQTT connected
> HASS setup for lock completed.
> -> FROM here
> **Attempting MQTT connection
> MQTT: Connecting without credentials
> MQTT disconnected. Reason: TCP_DISCONNECTED
> MQTT connect failed, rc=Free Heap: 101396
> Attempting MQTT connection
> MQTT: Connecting without credentials
> MQTT disconnected. Reason: TCP_DISCONNECTED
> MQTT connect failed, rc=Free Heap: 101600
> Attempting MQTT connection
> MQTT: Connecting without credentials
> MQTT disconnected. Reason: TCP_DISCONNECTED
> MQTT connect failed, rc=Free Heap: 113544
> Attempting MQTT connection
> MQTT: Connecting without credentials
> MQTT disconnected. Reason: TCP_DISCONNECTED
> MQTT connect failed, rc=Free Heap: 114588
> Attempting MQTT connection
> MQTT: Connecting without credentials
> MQTT connected
> HASS setup for lock completed.**
> -> TO here

My system information:

> NUKI Hub version: 8.31
> run: true
> deviceId: 2870512338
> deviceIdOp: 2870512338
> mqttbroker: 192.168.10.3
> mqttport: 1883
> mqttuser: 
> mqttpass: 
> mqttlog: false
> lockena: true
> mqttpath: nuki
> openerena: false
> mqttoppath: 
> maxkpad: 
> opmaxkpad: 
> mqttca: 
> mqttcrt: 
> mqttkey: 
> hassdiscovery: homeassistant
> dhcpena: false
> ipaddr: 192.168.4.3
> ipsub: 255.255.255.0
> ipgtw: 192.168.4.1
> dnssrv: 192.168.10.2
> nwhw: 1
> rssipb: 60
> hostname: nukihub
> nettmout: -1
> restdisc: true
> rstbcn: 60
> lockStInterval: 1800
> configInterval: 3600
> batInterval: 1800
> kpInterval: 1800
> kpEnabled: false
> accLvl: 0
> regAsApp: false
> nrRetry: 3
> rtryDelay: 100
> crdusr: ***
> crdpass: ***
> pubauth: false
> pubdbg: false
> prdtimeout: 60
> hasmac: false
> macb0: 
> macb1: 
> macb2: 
> MQTT connected: Yes
> Lock firmware version: 4.0.37
> Lock hardware version: 8.3
> Lock paired: Yes
> Lock PIN set: No
> Lock has door sensor: No
> Lock has keypad: No
> Network device: Built-in Wifi
> Uptime: 28 minutes
> Heap: 93540
> Stack watermarks: nw: 6104, nuki: 680, pd: 232
> Restart reason FW: ConfigurationUpdated
> Restart reason ESP: ESP_RST_SW: Software reset via esp_restart.

My ESP32: 
ESP32-WROOM-32D
(Is there a better ESP32 you can recommend?)

My network environment is run on Unifi.

**Comment by technyon** [comment]
I'm closing here, let's follow up in issue #236
