### ISSUE TITLE
Opener and KeyPad 2.0 - no KeyPad entities visible

### ISSUE THREAD

**Issue by gunnm80** [technyon/nuki_hub#298]
Hello
Thank you very much for the great work. I'm currently experimenting a bit.
I have an opener running via the ESP hub in the Home Assistant (2024.2.1). These entities are all displayed. But now I have also connected a KeyPad 2.0. Unfortunately, its entities are not displayed. I have already reset everything several times, reinstalled, recoupled... Without success. In other articles, I could see in pictures that entries such as "KeyPad status" should appear under "Diagnostic". In MQTT I receive corresponding messages from the KeyPad.
What am I doing wrong or what have I overlooked?
Thank you for your help.

![image](https://github.com/technyon/nuki_hub/assets/108416800/6261d559-e2c5-449b-9495-e3b33f31dc39)

![image](https://github.com/technyon/nuki_hub/assets/108416800/7f11085d-d51f-4567-aef1-58d470dfde2e)

![image](https://github.com/technyon/nuki_hub/assets/108416800/27d21230-e4cb-48fd-a413-f7c6c3939a57)

**Comment by technyon** [comment]
Try this binary.

[nuki_hub-8.33-pre-1.zip](https://github.com/technyon/nuki_hub/files/14260355/nuki_hub-8.33-pre-1.zip)

**Comment by gunnm80** [comment]
Sorry, maybe I'm a newbie. But how do I use this? Could not find this file on the Home Assistant via WinSC

**Comment by gunnm80** [comment]
![image](https://github.com/technyon/nuki_hub/assets/108416800/10dccfb7-15df-42c0-8d76-709476be7efb)

Are already one step further... Thank you. But in my opinion, entities of the KeyPad are still missing.  as "KeyPad status"

**Comment by gunnm80** [comment]
![image](https://github.com/technyon/nuki_hub/assets/108416800/2d7e9897-c9c6-4734-b901-713407ea982b)

**Comment by technyon** [comment]
I think the answer is unfortunately not as easy as adding the auto discovery topics for home assistant. Checking the code again, the keypad is actually not yet implemented for the opener - mostly because it's a rare thing that someone want's to use an opener and a keypad together. I'll have to go through the code and see what's necessary to add keypad support for the opener - it's mostly duplicating some code.

**Comment by gunnm80** [comment]
Thank you for your efforts. If there's anything I can do to help, I'm very happy to do it!

**Comment by gunnm80** [comment]
![image](https://github.com/technyon/nuki_hub/assets/108416800/77b8a30e-a962-4dd2-ab4d-08b6ff3b2210)

The view has changed...

**Comment by gunnm80** [comment]
with FingerPrint:

![image](https://github.com/technyon/nuki_hub/assets/108416800/975ef579-18bc-4e3d-8a0e-ed837a5364e6)

[
  {
    "index": 158,
    "authorizationId": 3431651,
    "authorizationName": "Keypad",
    "timeYear": 2024,
    "timeMonth": 2,
    "timeDay": 14,
    "timeHour": 8,
    "timeMinute": 51,
    "timeSecond": 46,
    "type": "KeypadAction",
    "action": "Unlock",
    "completionStatus": "undefined"
  },
  {
    "index": 157,
    "authorizationId": 3431651,
    "authorizationName": "Zutrittscode (Keypad)",
    "timeYear": 2024,
    "timeMonth": 2,
    "timeDay": 14,
    "timeHour": 8,
    "timeMinute": 50,
    "timeSecond": 52,
    "type": "KeypadAction",
    "action": "Unlock",
    "completionStatus": "success"
  },
  {
    "index": 156,
    "authorizationId": 3431651,
    "authorizationName": "Keypad",
    "timeYear": 2024,
    "timeMonth": 2,
    "timeDay": 14,
    "timeHour": 7,
    "timeMinute": 52,
    "timeSecond": 40,
    "type": "KeypadAction",
    "action": "Unlock",
    "completionStatus": "undefined"
  },
  {
    "index": 155,
    "authorizationId": 3431651,
    "authorizationName": "Zutrittscode (Keypad)",
    "timeYear": 2024,
    "timeMonth": 2,
    "timeDay": 14,
    "timeHour": 7,
    "timeMinute": 52,
    "timeSecond": 2,
    "type": "KeypadAction",
    "action": "Unlock",
    "completionStatus": "success"
  },
  {
    "index": 154,
    "authorizationId": 3431651,
    "authorizationName": "Keypad",
    "timeYear": 2024,
    "timeMonth": 2,
    "timeDay": 14,
    "timeHour": 7,
    "timeMinute": 48,
    "timeSecond": 43,
    "type": "KeypadAction",
    "action": "Unlock",
    "completionStatus": "undefined"
  }
]

**Comment by gunnm80** [comment]
With Pin:

![image](https://github.com/technyon/nuki_hub/assets/108416800/5f5982f0-ebba-4516-a3db-5c0e75b730f2)

[
  {
    "index": 159,
    "authorizationId": 3431651,
    "authorizationName": "Zutrittscode (Keypad)",
    "timeYear": 2024,
    "timeMonth": 2,
    "timeDay": 14,
    "timeHour": 8,
    "timeMinute": 54,
    "timeSecond": 5,
    "type": "KeypadAction",
    "action": "Unlock",
    "completionStatus": "success"
  },
  {
    "index": 158,
    "authorizationId": 3431651,
    "authorizationName": "Keypad",
    "timeYear": 2024,
    "timeMonth": 2,
    "timeDay": 14,
    "timeHour": 8,
    "timeMinute": 51,
    "timeSecond": 46,
    "type": "KeypadAction",
    "action": "Unlock",
    "completionStatus": "undefined"
  },
  {
    "index": 157,
    "authorizationId": 3431651,
    "authorizationName": "Zutrittscode (Keypad)",
    "timeYear": 2024,
    "timeMonth": 2,
    "timeDay": 14,
    "timeHour": 8,
    "timeMinute": 50,
    "timeSecond": 52,
    "type": "KeypadAction",
    "action": "Unlock",
    "completionStatus": "success"
  },
  {
    "index": 156,
    "authorizationId": 3431651,
    "authorizationName": "Keypad",
    "timeYear": 2024,
    "timeMonth": 2,
    "timeDay": 14,
    "timeHour": 7,
    "timeMinute": 52,
    "timeSecond": 40,
    "type": "KeypadAction",
    "action": "Unlock",
    "completionStatus": "undefined"
  },
  {
    "index": 155,
    "authorizationId": 3431651,
    "authorizationName": "Zutrittscode (Keypad)",
    "timeYear": 2024,
    "timeMonth": 2,
    "timeDay": 14,
    "timeHour": 7,
    "timeMinute": 52,
    "timeSecond": 2,
    "type": "KeypadAction",
    "action": "Unlock",
    "completionStatus": "success"
  }
]

**Comment by technyon** [comment]
Hi, I think first thing to do is to add the missing code, not that much you can do.

**Comment by gunnm80** [comment]
Hi
Any News?
best regards

**Comment by technyon** [comment]
Hi,

actually there's not as much missing as I thought. I think I only have to recheck all auto discoveries for the opener keypad

**Comment by technyon** [comment]
Check this binary please

[nuki_hub-8.34-pre-1.zip](https://github.com/technyon/nuki_hub/files/14469092/nuki_hub-8.34-pre-1.zip)

**Comment by gunnm80** [comment]
THX. much better. must test it.
![image](https://github.com/technyon/nuki_hub/assets/108416800/6cbeac5a-0310-48e7-9ff6-529ece5b1743)

**Comment by iranl** [comment]
Is this working as expected?

@technyon: Has this been merged into master yet?

**Comment by sjors-lemniscap** [comment]
I've manually build a `nuki_hub.bin` from https://github.com/technyon/nuki_hub/pull/373 and can confirm this is working. I've tested:

- Opener with a paired Keypad showing up correctly
- Deleting, updating, creating keycodes

**Comment by technyon** [comment]
Merged into master
