### ISSUE TITLE
ContinuousMode is displayed as locked

### ISSUE THREAD

**Issue by haibach-52** [technyon/nuki_hub#304]
ContinuousMode is displayed as locked in the web-frontend. In the app, however, you can see that CM is set.

![HGxoXgmO8l](https://github.com/technyon/nuki_hub/assets/67068686/00fdb53b-2904-470e-86c1-210b3fd6dbdd)
![firefox_utzYW6SQs2](https://github.com/technyon/nuki_hub/assets/67068686/3cbc65b2-3b4d-48c9-88c6-3bf92afadf82)

**Comment by technyon** [comment]
Hi, please wait for rekease 8.33
