### ISSUE TITLE
[Question] Is it safe to update the firmware on our NUKI? (and will it stay safe?)

### ISSUE THREAD

**Issue by Rubeast** [technyon/nuki_hub#307]
Hi! 

Not really an issue, but more a question.
I saw that my Nuki had a firmware update available. 
While it might be safe now to update, do you think it will stay safe?
I was wondering if they might able to block access to this hub in the future.

BTW: Love the NUKI-Hub. I even created a custom case for it.
![image](https://github.com/technyon/nuki_hub/assets/5304947/696b14a0-f99e-4ed9-bc8b-9cd248bc2943)
![image](https://github.com/technyon/nuki_hub/assets/5304947/d6b8322b-ec9d-40e6-ba78-a8b20788b837)

**Comment by technyon** [comment]
Nuki is actually supporting projects like this. The API for the bluetooth communication is available directly from Nuki, and there's a developer forum to ask questions.

Nuki Hub uses the same protocol that the smartphone app and the Nuki Bridge use. If they want to lock out third party implementations, they'd have to change the protocol and force users to update all devices connected to the lock ... a difficult thing to do.

I'd say don't worry too much, as this is endorsed by Nuki.

**Comment by Rubeast** [comment]
Ok. Great to hear!
