### ISSUE TITLE
Compilation information

### ISSUE THREAD

**Issue by jmsucasas** [technyon/nuki_hub#31]
This job is incredible,  I have lot of time searching a project like this!.
Is it possible to add some information to compile and create the bin file using the expressiff tools?

Thank you in advance,
BR

**Comment by technyon** [comment]
Check my other project which uses the same toolchain:

https://github.com/technyon/coffeetimer

You should configure the partition table to "minspiffs"

**Comment by rodriguezst** [comment]
You can also have a look at the GitHub Actions workflow file with all the steps needed to prepare the environment and compile the project at .github/workflows/build.yml

**Comment by jmsucasas** [comment]
It appears to be solved git-clonning nuki-ble library.  The directory nuki_hub seems to be empty when I git-clone the full project.

**Comment by technyon** [comment]
The nuki ble library is included as a submodule. You have to checkout with --recurse-submodules. It's not a good idea to manually clone the library into the nuki_ble directory.
