### ISSUE TITLE
Controlling the Nuki in Home Assistant

### ISSUE THREAD

**Issue by chrizstone** [technyon/nuki_hub#318]
I successfully configured an ESP32 with Nukihub and MQTT is connected and the lock is paired. How do I control it now in HA? Ist there an Add-on? How does it work? Sorry if this is a very nooby question...

**Comment by iranl** [comment]
RT(F)M: See the [README section about Home Assistant Discovery](https://github.com/technyon/nuki_hub?tab=readme-ov-file#home-assistant-discovery-optional)

TLDR: Assuming you have already setup the general MQTT integration in Home Assistant: Basically set "Home Assistant discovery topic" on the Nuki Hub "MQTT Configuration" page to "homeassistant".

**Comment by chrizstone** [comment]
Ok, I did that but cannot see any Lock devices in HA. Where can I see my default discovery topic in HA?
