### ISSUE TITLE
[Feature Request] Add support for ESP32-C6

### ISSUE THREAD

**Issue by cretzu8523** [technyon/nuki_hub#326]
I have a esp32-c6 board and I am not capable to install on it. Is this board compatible?

**Comment by iranl** [comment]
No, it is not compatible at this time.

ESP32 Arduino Core 3.0.0 (which is in alfa state right now) adds support for the C6.

Nuki Hub is build using the latest stable core 2.0.14

**Comment by technyon** [comment]
But even then it's not automatic, it would need a build targeting the C6. I still have to tinker with the C3, I couldn't get it running so far.

**Comment by lucaoliano** [comment]
Could I propose using PlatformIO? This would simplify the build process and the adoption of new boards. In this [branch of my fork](https://github.com/lucaoliano/nuki_hub/tree/platformio), I've introduced PlatformIO and configured three boards: the ESP32, the ESP32 Solo1 (Shelly 1 Plus), and the ESP32-S3 Dev Kit C1. You could check if the [binary for ESP32-S3](https://github.com/lucaoliano/nuki_hub/actions/runs/8491230545/artifacts/1371537422) works. 

To simplify the comparison, I didn't change the directory tree structure to match the PlatformIO one.

**Comment by technyon** [comment]
It should be possible to support both build systems, cmake and platformio, shouldn't it?

**Comment by lucaoliano** [comment]
I have removed some libraries from the lib folder and configured PlatformIO to download them. If you restore those libraries, you can build with CMake too. What advantages do you see in having both build systems?

**Comment by technyon** [comment]
Well, I know cmake quite well, it's powerful, and I can use clion for development.

**Comment by technyon** [comment]
Yeah except it doesn't really work, at least last time I checked. But really compiling this project isn't too hard. All the files are there, I somewhat like it in embedded projects to have all the files for compilation available without having to use some kind of package manager. Tried that for bigger projects (used conan for that). It works more or less, but gives you headaches often enough. Just copying the files into the project is often much less of a hassle for C/C++ projects.

**Comment by lucaoliano** [comment]
I don't use CLion so I don't know how well the PlatformIO plugin works, after your post I downloaded it and just tried to build the project and it built without any problems. Actually I'm using VSCode and it works pretty well with PlatformIO. In addition to the build and package management, also consider that can be supported different boards just by adding their ID in the configuration file.

**Comment by sjors-lemniscap** [comment]
> No, it is not compatible at this time.
> 
> ESP32 Arduino Core 3.0.0 (which is in alpha state right now) adds support for the C6.
> 
> Nuki Hub is build using the latest stable core 2.0.14

ESP32 Arduino Core 3.0.0 is now out of alpha (since 3 days): https://github.com/espressif/arduino-esp32/releases/tag/3.0.0

**Comment by iranl** [comment]
Preliminary/Experimental support for C6 is added in PR #407
This build is tested on a C6 devkit with nuki hub registered as an app.
There are still some issues though with stability (could partially be due to running as an app) and pairing.
Pairing can only be done by copying the pairing information of a different nuki hub device that is already paired.

**Comment by iranl** [comment]
ESP32-C6 should be usable once #436 is merged, including pairing.
