### ISSUE TITLE
Lock wont repair after unpair

### ISSUE THREAD

**Issue by aurelmarius** [technyon/nuki_hub#331]
I have a nuki lock 3 pro and because of poor battery life i want to try nuki hub. Installed latest version of nuki hub on an olimex poe iso board and paired to the lock. First pair went smooth, but in the morning i saw that nuki hub was reporting state unlocked, but nuki was locked. I tried to restart the esp board but no change. Then, I tried to re-pair the lock, but not working anymore.

**Comment by technyon** [comment]
Please factory reset your ESP and reflash NUKI Hub.

When paired again, please check if the smartphone app reports the correct status.

**Comment by aurelmarius** [comment]
I did factory reset, reflashed nuki hub, nothing works.
<img width="1374" alt="Screenshot 2024-03-25 at 15 15 45" src="https://github.com/technyon/nuki_hub/assets/7074653/d01597e4-87fd-4542-a7c4-6a7ddc32be02">

**Comment by aurelmarius** [comment]
Strange, after changing hub's hostname got paired.

**Comment by technyon** [comment]
is it reporting the state now correctly?

**Comment by aurelmarius** [comment]
Yes, untill now is reporting correctly and connection seems stable.![image](https://github.com/technyon/nuki_hub/assets/7074653/14ab5d43-904d-47ac-bcb9-2c265dc3b344)

**Comment by aurelmarius** [comment]
I will close this issue now, everything seems to work as expected. Thanks.

**Comment by technyon** [comment]
ok, perfect
