### ISSUE TITLE
OTA for 8.34 not possible

### ISSUE THREAD

**Issue by fir3drag0n** [technyon/nuki_hub#351]
just the erros appears:

```
Over-the-air update errored. Please check the logs for more info

Choose the updated nuki_hub.bin file to upload:
```

device: m5stack atom with poe/w5500
the log does not report anything special

```Nuki Hub version: 8.33
run: true
confVersion: 833
deviceId: 933569469
deviceIdOp: 961435431
mqttbroker: 192.168.1.191
mqttport: 1883
mqttuser: ***
mqttpass: ***
mqttlog: true
checkupdates: false
lockena: true
mqttpath: nuki
openerena: true
openercont: false
mqttoppath: nukiopener
maxkpad: 1
opmaxkpad: 
mqttca: 
mqttcrt: 
mqttkey: 
hassdiscovery: homeassistant
hassConfigUrl: 
dhcpena: true
ipaddr: 
ipsub: 
ipgtw: 
dnssrv: 
nwhw: 3
nwwififb: false
rssipb: 60
hostname: nukihub
nettmout: 40
restdisc: true
rstbcn: 60
lockStInterval: 1800
configInterval: 3600
batInterval: 1800
kpInterval: 1800
kpEnabled: true
accLvl: 0
regAsApp: false
nrRetry: 3
rtryDelay: 100
crdusr: 
crdpass: 
pubauth: false
pubdbg: false
prdtimeout: 60
hasmac: true
macb0: -84
macb1: -88
macb2: -90
MQTT connected: Yes
Lock firmware version: 4.1.8
Lock hardware version: 8.3
Lock paired: Yes
Lock PIN set: Yes
Lock has door sensor: Yes
Lock has keypad: Yes
Opener firmware version: 1.10.1
Opener hardware version: 4.17
Opener paired: Yes
Opener PIN set: Yes
Opener has keypad: Yes
Network device: Wiznet W5500
Uptime: 4 minutes
Heap: 139408
Stack watermarks: nw: 6136, nuki: 320, pd: 256
Restart reason FW: RestartOnDisconnectWatchdog
Restart reason ESP: ESP_RST_SW: Software reset via esp_restart.```

**Comment by iranl** [comment]
The binary in the ESP32 release file does not seem to be the proper binary. Please try the binary (nuki_hub_esp32.bin) from the 8.34 commit: https://github.com/technyon/nuki_hub/actions/runs/9031574144/artifacts/1490961864

@technyon: Is there a reason not to use the packages directly from GitHub actions?

I'm working on a PR to automate binary creation and uploading for releases.

**Comment by fir3drag0n** [comment]
thank  you! btw your discord link does not work anymore

**Comment by iranl** [comment]
Did you try https://discord.gg/24HxpGBJ ?

**Comment by capandcamera** [comment]
Binary being used by OTA does not have the .bin extension, 
8.34 was uploaded as nuki_hub. so the OTA downloads 8.33 again.

nuki_hub. | version bump to 8.34 | 2 hours ago
nuki_hub.bin | version bump to 8.33 | 2 months ago

**Comment by iranl** [comment]
Please try the binary that was linked in this issue or the new binary that was attached to the release

**Comment by noohi** [comment]
Thanks iranl.

OK, a bit embarrassing, and easily explainable, the POE device once flashed was not LAN by default, it was waiting for the WIFI setup first.
So long has passed since it worked upgrading itself, that I forgot the basics. One would assume it prioritizes LAN if available, but that's not important now.

So the last OTA update erased the network settings, that explains all on my side.

Anyway, for others in the future, if you have a POE/LAN ESP32 device like Olimex, note that nukihub is WIFI out of the box regardless.
After flashing connect to its AP, setup WIFI, change to LAN from Nukihub settings.

Btw thanks for the maintenance of the project!

**Comment by noohi** [comment]
Btw while at it, where is the network configuration to switchto v8.33?

**Comment by iranl** [comment]
Should be in the same spot as always, under `Network hardware` about halfway down under `Advanced MQTT and Network Configuration`

**Comment by noohi** [comment]
Thank you, all good now. (saw MQTT and eyes swiped over).
From today I officially lost the title of a power user :)

Suggestions from this:
- split MQTT and Network settings pages
- if possible to detect LAN presence, use it by default on first boot (if not set to anything specifically)

**Comment by technyon** [comment]
Hi,

Nuki Hub doesn't know what kind of ESP it's running on, and thus has no knowledge what kind of networking hardware is connected. All those boards that come with LAN have an external chip one way or another, so you first have to tell Nuki Hub what kind of chip is connected unfortunately.

**Comment by iranl** [comment]
Seems solved for all involved.

Starting from 8.35 release pipeline should be fully automatic so release binaries will be automatically added at all relevant locations at the same time (release, ota and webflash)
