### ISSUE TITLE
updating to 8.34 version

### ISSUE THREAD

**Issue by pilot1981** [technyon/nuki_hub#359]
Hi,
with new version 8.34 of Nuki hub I don't find correct nuki_hub.bin file to update my actual installation: can you give me more istruction howto update?

I don't found this info in wiki page...

regards

**Comment by technyon** [comment]
From the esp32-assets.zip archive, use the nuki_hub_esp32.bin file.

**Comment by pilot1981** [comment]
thanks

**Comment by jressel01** [comment]
Hello
I had the same problem. Which file do I have to take. I found this closed Topic 
A hint would be helpful.
