### ISSUE TITLE
Low performance in answer of Nuki

### ISSUE THREAD

**Issue by pilot1981** [technyon/nuki_hub#362]
Hi,
I would know if it’s normal that NUKI smart lock answer in more than 2 seconds…?

**Comment by pilot1981** [comment]
![IMG_0005](https://github.com/technyon/nuki_hub/assets/46350465/2bcc84c9-7555-4692-9857-fd431274ffe1)
![IMG_0004](https://github.com/technyon/nuki_hub/assets/46350465/e0245d2e-99b7-48e1-8d82-bc657203a391)

**Comment by iranl** [comment]
Yes, it is normal that communication between the ESP and lock takes several seconds. This is due to the nature of the BLE communication between the lock and ESP

**Comment by technyon** [comment]
See #361
