### ISSUE TITLE
[Feature Request] Nuki Keypad display authorization code information

### ISSUE THREAD

**Issue by sjors-lemniscap** [technyon/nuki_hub#382]
As explained on Discord the actual authorization code is not exposed in MQTT topics such as `lock/log` and `keypad/json` as a security measure.

It would be great to have an additional checkbox on the "**Nuki General Access Control**" page which allows the actual authorization code to be exposed.

**Comment by iranl** [comment]
Note that the code is not available as part of  the authorisation data published in `lock/log`. Nuki devices don't publish the code there.

**Comment by sjors-lemniscap** [comment]
> Note that the code is not available as part of the authorisation data published in `lock/log`. Nuki devices don't publish the code there.

Makes sense, `keypad/json` would be sufficient - don't think there are any other places.
