### ISSUE TITLE
_mqttMaxBufferSize filling most of the heap

### ISSUE THREAD

**Issue by rodriguezst** [technyon/nuki_hub#4]
I am implementing TLS support to MQTT to encrypt communications. It was working fine with version 2.6 (before opener support) but does not work now when rebasing to master.
It seems that there is no heap space available for the SSL due to an increase of the MQTT buffer.
`_mqttMaxBufferSize = 16384;`
If I decrease the value of _mqttMaxBufferSize from 16k to the default value (256bytes) it works fine.
Have you measured the maximum needed buffer? Are those 16k really needed?

**Comment by technyon** [comment]
16k is a bit excessive, I had to increase it due to the CSV-data not getting publishes if too many devices are present. I think it could be reduced to something more reasonable. Feel free to try; the question though is how many devices to support for presence detection.

I'll look into it later.

**Comment by technyon** [comment]
I've looked into it and there was a lot of memory to be saved. I never had the need to look into it, so I just kept it like this. I think you should have even more space available now than before 2.6.

**Comment by rodriguezst** [comment]
Thanks. It works fine now. I have submitted a PR with the TLS encryption changes.
