### ISSUE TITLE
How upgrade?

### ISSUE THREAD

**Issue by zaratustraelimpio** [technyon/nuki_hub#410]
Hi, 

how can I update the version of my nuki hub to new versions? I have 8.34 and I am having some problems and I have seen that if I access through the browser there is the "Upgrade firmware" option but it asks for a .bin file, which file should I do it with? with the complete .zip file? or is it one that is inside this one?,

thanks, 

regards.

**Comment by MihaiKrieger** [comment]
No. You click "Download latest binary from GitHub". a file with the extension .bin will be downloaded. You have to upload that one.

**Comment by zaratustraelimpio** [comment]
> No. You click "Download latest binary from GitHub". a file with the extension .bin will be downloaded. You have to upload that one.

Where i can download? Can you show me the link?

**Comment by jolichter** [comment]
> Where i can download? Can you show me the link?

Hi, can't you see this?
![image](https://github.com/technyon/nuki_hub/assets/1485851/e5f0eec8-e0a0-4b16-abc5-0f699e5ae1fb)

**Comment by iranl** [comment]
The "Download latest binary from GitHub" button is available on the nukihub/ota (Firmware upgrade) page, but only when the option "Check for updates every 24h" is enabled in the "MQTT and network" settings. This is where @MihaiKrieger is referring to.

When using the release zip (where @jolichter is referring to) you need to upload the nuki_hub_esp32[-S3/C3].bin file from inside the zip file.

You can also find this binary on github in the /ota directory.

**Comment by sebax80** [comment]
where is the upload file

![immagine](https://github.com/technyon/nuki_hub/assets/64022736/97997cd8-adfd-4446-bf71-5aab8048e414)

**Comment by iranl** [comment]
Please just read the comments above.

`You can also find this binary on github in the /ota directory`

**Comment by sebax80** [comment]
Please tell me what should I do to get help to upgrade?

**Comment by MihaiKrieger** [comment]
1. Open the IP address of your Nukihub (local IP on your network)
You shoould see this:

![image](https://github.com/technyon/nuki_hub/assets/52798790/5c27ff08-6a7d-4e7e-9a2d-9ef3283eb947)

2. click on the option „Firmware update”. You should get this:

![image](https://github.com/technyon/nuki_hub/assets/52798790/dfc40a0a-b3d5-4269-a69b-fb33ce8aa45d)

3. Click on: „Download latest binary from GitHub” . Like this:
![image](https://github.com/technyon/nuki_hub/assets/52798790/bd00a12a-bf15-4ee5-b227-ffe3b285990d)


4. Download the file called **nuki_hub_esp32.bin** to your desktop.

5. Choose the file you have just downloaded from here: 
![image](https://github.com/technyon/nuki_hub/assets/52798790/1f2dfe75-4edf-4f24-a412-0ff39f6d77f3)

6. With the file inserted in that field, click on „Upload file”. The web interface does its job than.
![image](https://github.com/technyon/nuki_hub/assets/52798790/638f4539-72b7-463e-b342-174fde8610b4)
