### ISSUE TITLE
problem update at 8.35

### ISSUE THREAD

**Issue by sebax80** [technyon/nuki_hub#412]
Good morning, or version 8.33, trying to run version 8.35 I can't find the file

![immagine](https://github.com/technyon/nuki_hub/assets/64022736/662723a0-1e9d-4542-ab6a-3b2d6157255b)

![immagine](https://github.com/technyon/nuki_hub/assets/64022736/305bf78b-f9bd-4109-b3c8-f79e68c9b24d)

**Comment by iranl** [comment]
If you had followed the issue template instead of deleting it you would have found that:
A: Issues are not meant for questions, that is where discussions are for
B: Your question has been asked and answered in the README and in earlier issues such as #410

Closing
