### ISSUE TITLE
Battery "level" is missing in version 8.35

### ISSUE THREAD

**Issue by gerardovf** [technyon/nuki_hub#414]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._
Payload in homeassistant configuration ("value") does not match with the name sent afterwards ("batteryVoltage")

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ x] Read the [Contributing Guide and Policy](https://github.com/technyon/nuki_hub/blob/master/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/technyon/nuki_hub/blob/master/CODE_OF_CONDUCT.md)
- [ x] Searched the problem in [issues](https://github.com/technyon/nuki_hub/issues)
- [ x] Searched the problem in [discussions](https://github.com/technyon/nuki_hub/discussions)
- [x ] Searched the problem in the [docs](https://github.com/technyon/nuki_hub)
- [ ] Searched the problem in the [chat](https://discord.gg/9nPq85bP4p)
- [x ] Device used (e.g., ESP32-S3): ESP32-S3
- [x ] Nuki Hub binary firmware version number used: 8.35
  - [ x] Pre-compiled
  - [ ] Self-compiled
- [ ] Provide the output of http://nukihubIP/info:
```

```

### TO REPRODUCE
_Steps to reproduce the behavior:_
In MQTT Explorer:
homeassistant/sensor/3a09c085/battery_voltage/config
{"dev":{"ids":["nuki_3a09c085"],"mf":"Nuki","mdl":"SmartLock","name":"PetinMainDoor"},"~":"gvf/cega/nukipetin1","name":"Battery voltage","unique_id":"3a09c085_battery_voltage","dev_cla":"voltage","stat_t":"~/battery/advancedJson","stat_cla":"measurement","ent_cat":"diagnostic","avty":{"t":"gvf/cega/nukipetin1/maintenance/mqttConnectionState"},"unit_of_meas":"V","val_tpl":"**{{value_json.level}}**"}

gvf/cega/nukipetin1/battery/advancedJson
{"batteryDrain":247,**"batteryVoltage":5.386**,"critical":196,"lockAction":"Unlatch","startVoltage":5.368,"lowestVoltage":3.2,"lockDistance":0.094,"startTemperature":31,"maxTurnCurrent":2.672,"batteryResistance":0.811}

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by iranl** [comment]
Thanks for the report.
Can confirm.
Fixed in #407

**Comment by gerardovf** [comment]
THANKs!!!
