### ISSUE TITLE
Nuki Lock freezes(goes offline) after a while when connected to Nuki Hub

### ISSUE THREAD

**Issue by Andrecall** [technyon/nuki_hub#432]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._
Nuki Lock 4.0 Pro freezes/goes offline after 20-30h being connected to Nuki Hub, stops being available via BT. It happens only when Lock ist connected to Nuki Hub. The Nuki Lock becomes not available even via original app. The only one fix, that works: remove the battery and put it back 
Tried with FW 8.34 and FW 8.35 - No changes.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ x] Read the [Contributing Guide and Policy](https://github.com/technyon/nuki_hub/blob/master/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/technyon/nuki_hub/blob/master/CODE_OF_CONDUCT.md)
- [ x] Searched the problem in [issues](https://github.com/technyon/nuki_hub/issues)
- [ x] Searched the problem in [discussions](https://github.com/technyon/nuki_hub/discussions)
- [x ] Searched the problem in the [docs](https://github.com/technyon/nuki_hub)
- [ ] Searched the problem in the [chat](https://discord.gg/9nPq85bP4p)
- [x ] Device used (e.g., ESP32-S3): M5 Atom S3 Lite
- [ x] Nuki Hub binary firmware version number used: FW 8.34 and FW 8.35
  - [ x] Pre-compiled
  - [ ] Self-compiled
- [ x] Provide the output of http://nukihubIP/info:
```
Lock config ACL (Timezone offset): Disallowed
Lock config ACL (DST mode): Disallowed
Lock config ACL (Fob Action 1): Disallowed
Lock config ACL (Fob Action 2): Disallowed
Lock config ACL (Fob Action 3): Disallowed
Lock config ACL (Single Lock): Allowed
Lock config ACL (Advertising Mode): Disallowed
Lock config ACL (Timezone ID): Disallowed
Lock config ACL (Unlocked Position Offset Degrees): Disallowed
Lock config ACL (Locked Position Offset Degrees): Disallowed
Lock config ACL (Single Locked Position Offset Degrees): Disallowed
Lock config ACL (Unlocked To Locked Transition Offset Degrees): Disallowed
Lock config ACL (Lock n Go timeout): Disallowed
Lock config ACL (Single button press action): Disallowed
Lock config ACL (Double button press action): Disallowed
Lock config ACL (Detached cylinder): Disallowed
Lock config ACL (Battery type): Disallowed
Lock config ACL (Automatic battery type detection): Disallowed
Lock config ACL (Unlatch duration): Disallowed
Lock config ACL (Auto lock timeout): Disallowed
Lock config ACL (Auto unlock disabled): Allowed
Lock config ACL (Nightmode enabled): Disallowed
Lock config ACL (Nightmode start time): Disallowed
Lock config ACL (Nightmode end time): Disallowed
Lock config ACL (Nightmode auto lock enabled): Disallowed
Lock config ACL (Nightmode auto unlock disabled): Disallowed
Lock config ACL (Nightmode immediate lock on start): Disallowed
Lock config ACL (Auto lock enabled): Allowed
Lock config ACL (Immediate auto lock enabled): Disallowed
Lock config ACL (Auto update enabled): Disallowed
Network device: Built-in Wi-Fi
Uptime: 634 minutes
Heap: 141228
Stack watermarks: nw: 7712, nuki: 2328, pd: 96
Restart reason FW: BLEBeaconWatchdog
Restart reason ESP: ESP_RST_SW: Software reset via esp_restart.
```

### TO REPRODUCE
_Steps to reproduce the behavior:_
Pair Nuki Lock 4 Pro to Nuki Hub, wait for 1-2 days

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._
Lock continues doesn't go offline after couple days and continues to be available via BT with the original Nuki App.

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by technyon** [comment]
This sounds really strange, I'm running Nuki Hub (latest beta) for days without issues, as do many other users. It'll be hard to give you specific advice, maybe you can try the latest beta for now:

https://github.com/technyon/nuki_hub/actions/runs/10069081312

If that doesn't help, maybe consider doing a factory reset on your lock, I've fixed a few strange issues like this by just resetting Nuki hardware.

**Comment by iranl** [comment]
This might be an issue with the S3 (and other non original ESP32's)

I have been experiencing something similar, but because I use Hybrid mode on my devices I'm not really impacted in a big way.

#436 is intended to fix this.

**Comment by Andrecall** [comment]
> This might be an issue with the S3 (and other non original ESP32's)
> 
> I have been experiencing something similar, but because I use Hybrid mode on my devices I'm not really impacted in a big way.
> 
> #436 is intended to fix this.

So using the latest beta from [here](https://github.com/technyon/nuki_hub/actions/runs/10069081312) should potentially solve the issue then?

**Comment by iranl** [comment]
No, unmerged PRs are not included in nightlies.

You would need a binary from https://github.com/technyon/nuki_hub/actions/runs/10084431827

Note that updating from 8.35 to 9.0 release/beta/nightly requires a usb/serial flash once using the instructions in the how-to-flash.txt file

**Comment by Andrecall** [comment]
> No, unmerged PRs are not included in nightlies.
> 
> You would need a binary from https://github.com/technyon/nuki_hub/actions/runs/10084431827
> 
> Note that updating from 8.35 to 9.0 release/beta/nightly requires a usb/serial flash once using the instructions in the how-to-flash.txt file

Thank you for a quick reply! I'll try this version (non-debug, right?) and will share an update. Due to the nature of bug, it could take 2-3 days before I could provide any feedback

**Comment by iranl** [comment]
Debug version is not necessary

**Comment by Andrecall** [comment]
Ok, got the results earlier than expected. Unfortunately the problem stays the same: after some time Lock becomes unavailable via BT (neither from Nuki Hub nor Original app). This only happens if Lock is connected to Nuki Hub and not using builtin WiFi/MQTT

**Comment by iranl** [comment]
Please post the complete output of http://nukihubIP/info at the time you notice the lock is unavailable

**Comment by Andrecall** [comment]
> Please post the complete output of http://nukihubIP/info at the time you notice the lock is unavailable

I think I've already posted it in the original message. Or should I post it for the new FW(9.00)?

**Comment by iranl** [comment]
It is incomplete in your first post

**Comment by Andrecall** [comment]
Unfortunately the issue is not solved yet, I'm just on vacation now and therefore not able to collect info data from the Nuki hub. I'll be back soon and will share the required details

**Comment by iranl** [comment]
First update to the latest beta binaries, than post a complete info page and when this issue persists post serial logs when the issue occurs

**Comment by andresledo** [comment]
I have the same issue, with latest beta...

**Comment by iranl** [comment]
@engst03 Thanks for the info. 

I have actually been experiencing something of the same nature as @Andrecall recently. Sometimes my keypad 2 and fobs can't connect to my nuki 4.0 pro. Only removing battery of the lock will fix it. Thread/Matter does seem to stay functional.

I have experienced this behaviour with and without Nuki Hub connected, so this more and more does not seem to be related to NH. 

Nuki devs, as I understand, have confirmed that the total amount of connections/queries to the lock do seem to exacerbate/hasten the issues, so that is why/how having NH running can lead to more/earlier issues.

Solution does seem to be on the side of Nuki though and not on our side.

Nuki has released 4.4.1 beta firmware which should fix this bug. I'm going to be testing this myself in the coming weeks.

**Comment by DeckardCain2014** [comment]
Hi, any update here? I also have the issues with the lock freezing after several days of usage with the ESP nuki hub.
The issue seems not be solved on Nuki side.

**Comment by technyon** [comment]
What version of Nuki Hub are you running?

**Comment by DeckardCain2014** [comment]
the latest, v9.06

**Comment by iranl** [comment]
Please don't necropost other users resolved issues of six month ago with outdated versions of NukiHub. If you believe there is an issue with a recent version of NukiHub create your own issue and follow the issue template
