### ISSUE TITLE
status  lock does not update

### ISSUE THREAD

**Issue by sebax80** [technyon/nuki_hub#439]
The status does not update and remains undefined, what will be the problem? the rest all works, both locking and unlocking

![immagine](https://github.com/user-attachments/assets/d990130d-01ee-43c8-81e8-60bc3322472c)

**Comment by iranl** [comment]
Please use the issue template and follow it. Than you would have found the answer in #406 or #417

**Comment by technyon** [comment]
I've added a comment to the readme, we can remove it once 9.0 is released.
