### ISSUE TITLE
Remove Unlatch to Home Assistant ?

### ISSUE THREAD

**Issue by Balooforever** [technyon/nuki_hub#446]
Hi everyone,

Thank a lot for your works !

I'm beginner with Nuki Hub 9.0 and i have only one little problem. I can't disable the "Unlatch" discovery to my home assistant. My door can't do this and i want to disable the button on home assistant.

How i can do it ?
 
I have "unceck" "Unlatch" in nuki hub but nothing happen..

Thank a lot :)

**Comment by iranl** [comment]
Closing for not following the issue template.
You can reopen once you have filled in the template
