### ISSUE TITLE
[Feature Request] Disable the "Unlatch" discovery

### ISSUE THREAD

**Issue by Balooforever** [technyon/nuki_hub#447]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._

Hi everyone,

Thank a lot for your works !

I'm beginner with Nuki Hub 9.0 and i have only one little problem. I can't disable the "Unlatch" discovery to my home assistant. My door can't do this and i want to disable the button on home assistant.

How i can do it ?

I have "unceck" "Unlatch" in nuki hub but nothing happen..

Thank a lot :)

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [X] Read the [Contributing Guide and Policy](https://github.com/technyon/nuki_hub/blob/master/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/technyon/nuki_hub/blob/master/CODE_OF_CONDUCT.md)
- [X] Searched the problem in [issues](https://github.com/technyon/nuki_hub/issues)
- [X] Searched the problem in [discussions](https://github.com/technyon/nuki_hub/discussions)
- [X] Searched the problem in the [docs](https://github.com/technyon/nuki_hub)
- [X] Searched the problem in the [chat](https://discord.gg/9nPq85bP4p)
- [X] Device used (e.g., ESP32-S3): M5 Atom Light
- [X] Nuki Hub binary firmware version number used: 9.0
  - [X] Pre-compiled
- [X] Provide the output of http://nukihubIP/info:
```
Nuki Hub version: 9.00
Nuki Hub build: 10235422676.1.1
Nuki Hub build type: Release
run: true
confVersion: 900
deviceId: 231675750
deviceIdOp: 231675750
nukiId: ***
nukidOp: 
mqttbroker: 192.168.1.65
mqttport: 1883
mqttuser: ***
mqttpass: ***
mqttlog: false
checkupdates: false
websrvena: false
lockena: true
lockpin: 1
mqttpath: nuki
openerena: false
openerpin: 
openercont: false
mqttoppath: 
maxkpad: 
opmaxkpad: 
maxtc: 
opmaxtc: 
enabtlprst: false
mqttca: 
mqttcrt: 
mqttkey: 
hassdiscovery: homeassistant
hassConfigUrl: 
buffsize: 
dhcpena: true
ipaddr: 
ipsub: 
ipgtw: 
dnssrv: 
nwhw: 1
nwwififb: false
rssipb: 60
hostname: nukihub
nwbestrssi: false
nettmout: -1
restdisc: false
rstbcn: -1
lockStInterval: 1800
tcPerEntry: false
kpPerEntry: false
configInterval: 3600
batInterval: 1800
kpInterval: 1800
kpCntrlEnabled: true
kpInfoEnabled: false
kpPubCode: false
tcCntrlEnabled: false
tcInfoEnabled: false
cnfInfoEnabled: true
regAsApp: false
regOpnAsApp: false
nrRetry: 3
rtryDelay: 100
crdusr: ***
crdpass: ***
disnonjson: false
pubAuth: false
pubdbg: false
prdtimeout: 
offHybrid: false
hybridTimer: 600
hybridAct: false
hybridRtry: false
hasmac: false
macb0: 
macb1: 
macb2: 
latest: 
tsksznetw: 
tsksznuki: 
authmaxentry: 
kpmaxentry: 
tcmaxentry: 
updMqtt: false
showSecr: false
bleTxPwr: 
recNtwMqttDis: false
MQTT connected: Yes
Lock firmware version: 3.9.5
Lock hardware version: 4.10
Lock paired: Yes
Lock valid PIN set: Yes
Lock has door sensor: No
Lock has keypad: No
Lock ACL (Lock): Allowed
Lock ACL (Unlock): Allowed
Lock ACL (Unlatch): Disallowed
Lock ACL (Lock N Go): Allowed
Lock ACL (Lock N Go Unlatch): Disallowed
Lock ACL (Full Lock): Allowed
Lock ACL (Fob Action 1): Allowed
Lock ACL (Fob Action 2): Allowed
Lock ACL (Fob Action 3): Allowed
Lock config ACL (Name): Allowed
Lock config ACL (Latitude): Allowed
Lock config ACL (Longitude): Allowed
Lock config ACL (Auto Unlatch): Allowed
Lock config ACL (Pairing enabled): Allowed
Lock config ACL (Button enabled): Allowed
Lock config ACL (LED flash enabled): Allowed
Lock config ACL (LED brightness): Allowed
Lock config ACL (Timezone offset): Allowed
Lock config ACL (DST mode): Allowed
Lock config ACL (Fob Action 1): Allowed
Lock config ACL (Fob Action 2): Allowed
Lock config ACL (Fob Action 3): Allowed
Lock config ACL (Single Lock): Allowed
Lock config ACL (Advertising Mode): Allowed
Lock config ACL (Timezone ID): Allowed
Lock config ACL (Unlocked Position Offset Degrees): Allowed
Lock config ACL (Locked Position Offset Degrees): Allowed
Lock config ACL (Single Locked Position Offset Degrees): Allowed
Lock config ACL (Unlocked To Locked Transition Offset Degrees): Allowed
Lock config ACL (Lock n Go timeout): Allowed
Lock config ACL (Single button press action): Allowed
Lock config ACL (Double button press action): Allowed
Lock config ACL (Detached cylinder): Allowed
Lock config ACL (Battery type): Allowed
Lock config ACL (Automatic battery type detection): Allowed
Lock config ACL (Unlatch duration): Allowed
Lock config ACL (Auto lock timeout): Allowed
Lock config ACL (Auto unlock disabled): Allowed
Lock config ACL (Nightmode enabled): Allowed
Lock config ACL (Nightmode start time): Allowed
Lock config ACL (Nightmode end time): Allowed
Lock config ACL (Nightmode auto lock enabled): Allowed
Lock config ACL (Nightmode auto unlock disabled): Allowed
Lock config ACL (Nightmode immediate lock on start): Allowed
Lock config ACL (Auto lock enabled): Allowed
Lock config ACL (Immediate auto lock enabled): Allowed
Lock config ACL (Auto update enabled): Allowed
Network device: Built-in Wi-Fi
BSSID of AP: %%
Uptime: 145 minutes
Heap: 79528
Stack watermarks: nw: 8272, nuki: 4948
Restart reason FW: WifiInitFailed
Restart reason ESP: ESP_RST_SW: Software reset via esp_restart.
```

### TO REPRODUCE
_Steps to reproduce the behavior:_
Expose lock to home assistant

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by iranl** [comment]
Edit your comment with the ouput or http://nukihubip/info or your issue will be closed again in accordance with the Contributing policy.
Do not open new issues but edit your earlier comment.

Also provide information of what exact home asissistant entity you expect to be removed with it's entity id and/or screenshots of the place(s) you expect this to be removed

**Comment by Balooforever** [comment]
I don't understand why add sur "info" with this issue but, OK, i have add it, contributing policy is little hardcore oO

I want to remove this in purple : 

![image](https://github.com/user-attachments/assets/38da2f2a-14a6-4659-8004-8b126a759d5b)

Nuki hub expose "Unlatch", but my door doesn't have unlatch, i doesn't want it to home assistant.

**Comment by iranl** [comment]
The contributing policy explains why we need the template filled.

What you are asking is not possible in 9.0

I've added it to PR #445, once this is merged you can update to a development version using the firmware update page on the web configurator or wait for release/beta of 9.01

**Comment by Balooforever** [comment]
Thank, no urgency, wainting release, thx :)
