### ISSUE TITLE
/src/updater/release/esp32/updater.bin: No such file or directory

### ISSUE THREAD

**Issue by marcospazianibrunella** [technyon/nuki_hub#449]
I downloaded the latest from the repo and when trying to build with Docker, I get the following error
<img width="1264" alt="image" src="https://github.com/user-attachments/assets/83ccbaae-6805-4ec7-be0d-3041567cf7e8">

Same thing if I build on Ubuntu without Docker

**Comment by technyon** [comment]
Hi. Yes I noticed, not sure why. For now it helps to just download a release and copy the updater binary there.

**Comment by iranl** [comment]
Fixed in #450
