### ISSUE TITLE
[SECURITY] Previous Auth Name in nukiopener/lock/json

### ISSUE THREAD

**Issue by alexlenk** [technyon/nuki_hub#472]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._

In the nukiopener/lock/json transmitted to the MQTT broker the "auth_name" field is not up to date. It is from the last opening action and not the current one. This means that checking for who opened the door and execute action based on this will result in wrong access right.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Read the [Contributing Guide and Policy](https://github.com/technyon/nuki_hub/blob/master/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/technyon/nuki_hub/blob/master/CODE_OF_CONDUCT.md)
- [ ] Searched the problem in [issues](https://github.com/technyon/nuki_hub/issues)
- [ ] Searched the problem in [discussions](https://github.com/technyon/nuki_hub/discussions)
- [ ] Searched the problem in the [docs](https://github.com/technyon/nuki_hub)
- [ ] Searched the problem in the [chat](https://discord.gg/9nPq85bP4p)
- [ ] Device used (e.g., ESP32-S3): _____
- [ ] Nuki Hub binary firmware version number used: _____
  - [ ] Pre-compiled
  - [ ] Self-compiled
- [ ] Provide the output of http://nukihubIP/info:
```

```

### TO REPRODUCE
_Steps to reproduce the behavior:_

1. Open the Nuki Opener via MQTT/HomeAssistant. This changes the Auth Name to: "NukiHub"
2. Open the Nuki Opener with the App or Keypad. In this MQTT message should now the authenticated user be set as "Auth Name". It is, however, still "NukiHub"

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

Have the correct Auth Name from the person who executes the action

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by iranl** [comment]
Please complete the template as required by our code of conduct. This will help exclude misconfiguration on your part as a cause of the issue.
