### ISSUE TITLE
Missing GitHub release 9.01

### ISSUE THREAD

**Issue by duhow** [technyon/nuki_hub#517]
Small comment but, as of 8912a84521d719600fa087ceb962281405edad32 ,
I understand that 9.01 is already released and tagged, but does not show in GitHub Releases 👉🏻 👈🏻

**Comment by iranl** [comment]
9.01 was pulled from GitHub shortly after for not being deemed a good enough release with a couple of new features/changes reverted immediately in 9.02.

It should have been pulled from the OTA manifest but wasn't. Please use the latest beta of 9.02 which is nearing final or stay on 9.00
