### ISSUE TITLE
MQTT Invalid event type "standby" for ring

### ISSUE THREAD

**Issue by duhow** [technyon/nuki_hub#518]
### PROBLEM DESCRIPTION

Received ⚠️ warning in Home Assistant:

> Invalid event type standby for event.portero_ring received on topic `nuki/opener/ring`, payload `{ "event_type": "standby" }`

https://github.com/technyon/nuki_hub/blob/6a08e2690b70137d1b17689400b0269662b0d4ee/src/HomeAssistantDiscovery.cpp#L1955-L1956

Current supported events seem to be `ring` and `ringlocked`, but status sent are `ring` and `standby`.

https://github.com/technyon/nuki_hub/blob/6a08e2690b70137d1b17689400b0269662b0d4ee/src/HomeAssistantDiscovery.cpp#L1949-L1950

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/technyon/nuki_hub/blob/master/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/technyon/nuki_hub/blob/master/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/technyon/nuki_hub/issues)
- [x] Searched the problem in [discussions](https://github.com/technyon/nuki_hub/discussions)
- [x] Searched the problem in the [docs](https://github.com/technyon/nuki_hub)
- [x] Searched the problem in the [chat](https://discord.gg/9nPq85bP4p)
- [x] Device used (e.g., ESP32-S3): ESP32
- [x] Nuki Hub binary firmware version number used: 9.02-beta4
  - [x] Pre-compiled
  - [ ] Self-compiled

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by iranl** [comment]
Tnx for the report.

Simultaneous development on refractor of HA in #515 and ring detection fixes in #512 caused this part of #512 to disappear from master.
