### ISSUE TITLE
Nuki Opener: How to pair (as app) with the nuki_hub

### ISSUE THREAD

**Issue by massaquah** [technyon/nuki_hub#52]
Hi,
I am desperately trying to pair my nuki opener to the nuki hub.
The procedure for the nuki lock was clear: press the button 5 seconds and (re)start the esp32.
But I am not able to connect the opener.
What am I doing wrong?

In the esp32 log I can see that the device is trying to pair with the opener at least...

![image](https://user-images.githubusercontent.com/6074180/205096660-933ba065-6bb9-428b-817d-c19bba8fc256.png)

**Comment by massaquah** [comment]
obviously related to #39

**Comment by technyon** [comment]
Not so sure, pairing to the lock works in this case. Did you turn on pairing mode for the opener (same as for the lock, long press ~5 sec I believe)?
