### ISSUE TITLE
2 nuki smart lock in the same house

### ISSUE THREAD

**Issue by pilot1981** [technyon/nuki_hub#54]
Hi,
I have a Nuki smart lock 3.0 (only BLE) and a Nuki smart lock 3.0 pro (BLE+WIFI) in the same house. they are not accesible via BLE from an unique point.

I can use only one ESP32 to control both smart locks? it can connect via BLE near to Smart Lock 3.0 and via WIFI to the Smart lock 3.0 Pro?

or I have to use n.2 ESP32? one dedicated for each Smart lock?

regards

**Comment by technyon** [comment]
Hi,

Each ESP can only control one lock and one opener, so you need two ESPs to control two locks.

You can only connect via bluetooth to the lock, but if you have A Pro lock, you can eventually connect it directly without the need of an ESP with all advantages and disadvantages.

Considering how cheap ESPs are, maybe just two and you're set up.

**Comment by pilot1981** [comment]
Thanks for reply, you know how to connect directly HA and NUKI smart lock 3.0 pro (WIFI version)?

I don’t find API token…

**Comment by pilot1981** [comment]
I found a way to use API token via Julie web access.

you think using ESP32 I can save battery of NUKI smart lock 3.0 pro?

**Comment by technyon** [comment]
If you disable Wifi and use the ESP instead, you'll save battery.

**Comment by pilot1981** [comment]
Hi,
Today I tested your firmware with my NUKI smart lock 3.0: installation works fine and MQTT and NUKI connection are OK, but when I send unlock command from HA: it don’t works!

how I can troubleshoot it?

**Comment by technyon** [comment]
You did successfully pair it? Do you values reported in HA like battery level? If yes, browse the MQTT tree and see if the lock/action node is set when you send the unlock command from HA.

**Comment by pilot1981** [comment]
![B2E7B0C6-673C-49D3-9FFF-E0C556468172](https://user-images.githubusercontent.com/46350465/206480714-c1b3a1f4-7d63-4169-ae9d-f8ab0d8bb6ea.png)
![FDF9715A-E48B-45CB-8F4E-A18C22203EF7](https://user-images.githubusercontent.com/46350465/206480718-2cb642c3-78ca-4482-884f-e10d7149dadc.png)
![1C8E1E2B-3C41-4B06-AF97-97CA2C270030](https://user-images.githubusercontent.com/46350465/206480721-dfed362b-b4bd-4e9f-845f-67aefbdc9a95.png)

**Comment by pilot1981** [comment]
State of casetta is wrong:
![2C6DBCAC-BA6B-492E-91D4-B3351C73BEC0](https://user-images.githubusercontent.com/46350465/206480982-52127648-580c-4307-b136-7a4d446285e2.png)

**Comment by technyon** [comment]
Can you try to directly set the "lock/action" node to "lock" or "unlock" and see if you have delays. The question is where the action gets lost. Doesn't HA send the action, does the MQTT broker somehow not forward it (maybe because MQTT is disconnected at the time), or does the command get sent to the ESP, but somehow bluetooth communication fails. Any of those can fail, and we need to isolate the broken link.

**Comment by pilot1981** [comment]
Hi,
I added PIN code in credential section of NUKIhub.

I tried to launch service unlock from Lovelace and from tool services of Ha But nothing happened.

I red mqtt messages from broker, I suppose connection are good.

I attach MQTT messages:

![CE0E4125-0D5A-41F3-946F-7DDCAD59F4D0](https://user-images.githubusercontent.com/46350465/206571012-8cfe7b24-1f67-4233-9b88-9ace1f97c85e.png)
![12BD1C24-2140-45BF-AA41-594B392E88FF](https://user-images.githubusercontent.com/46350465/206571021-702ad8b8-6035-4fa9-8fb0-63e157f5271b.png)
![48A415D3-3172-4108-881D-C4A6014F5A27](https://user-images.githubusercontent.com/46350465/206571025-3b9d4e4a-5ff8-4ac3-ac04-d4015731fcfd.png)
![DEBE5477-ED6F-4454-A244-A93F69373AB6](https://user-images.githubusercontent.com/46350465/206571032-e58b035a-62bb-49ed-a233-81b5c3eb4297.png)
![82E1D0FD-AF37-4B39-92DF-DCB444F3234F](https://user-images.githubusercontent.com/46350465/206571034-3f179b0c-1c05-4a0d-be18-7ebe191767e7.png)
![FFCED153-A8EA-433B-93D6-5FCD35AED4CE](https://user-images.githubusercontent.com/46350465/206571036-2915c4be-5c2d-49f4-8a17-e4b856201c95.png)

**Comment by technyon** [comment]
I think you should take care of the "Error: This client is not authorized."

**Comment by pilot1981** [comment]
sorry, this one is a client mis configuration...not our problem...

**Comment by pilot1981** [comment]
I also have to setup username e password?

**Comment by technyon** [comment]
Hi, if your MQTT broker is configured with a username and a password, you'll have to give it to NUKI Hub so it can connect to the broker. However, it says "MQTT connected: Yes" in your picture, so all is fine. I guess the error message is about some other device.

Can you download some MQTT client and set the "lock/action" node as described. This would really help because it takes home assistant out of the equasion and we can see if this is HA related or not.

**Comment by pilot1981** [comment]
Sure, I go to use an MQTT client to send unlock command to MQTT broker Mosquitto Installed on my HA!

I let you know!

**Comment by pilot1981** [comment]
Hi,
I tried and all works fine:

![Cattura_schermata_-_10_dic__0_50_PM](https://user-images.githubusercontent.com/46350465/206853667-dadb7d6e-2adc-4d17-bc9a-eedd6ca224d5.png)

**Comment by pilot1981** [comment]
![image](https://user-images.githubusercontent.com/46350465/206853703-407092aa-1497-474d-bbf0-e179c419f8db.png)

**Comment by pilot1981** [comment]
ok, now all works also from HA. I don't changed anything...I don't understand...

thanks for your help and your work!

**Comment by technyon** [comment]
ok glad to hear.
