### ISSUE TITLE
It should ignore command in queue after restart

### ISSUE THREAD

**Issue by ciddi89** [technyon/nuki_hub#56]
Hi,
first at all, thank you for the work! It's a great project!

Here is my problem:

Sometimes I have to restart the ESP by myself because it has no connection anymore. But after the restart It will run the last command which I sent over MQTT while it was unreachable. Is there any way to Ignore that? 
When I'm staying at home and restart it, it's no problem I'm there. But in case there is an power outage and I'm not at home and for whatever reason there is an command in queue like to open the door and the power is back. I think it's not good when the door will open then. :) I hope you understand my concern and maybe there is something to fix it. 

For your information: I'm using Firmware v6.2 with ESP32 CP2102 over MQTT to ioBroker.

Anyway thanks again.

**Comment by technyon** [comment]
Good observation. Should be fixed in release 6.3. It will also ignore actions after a reconnect, because it could have the same effect: Wifi goes down for some reason for an extended time, the action would trigger after the reconnect.
