### ISSUE TITLE
MQTT GPIO messages not retained

### ISSUE THREAD

**Issue by VDRainer** [technyon/nuki_hub#567]
### PROBLEM DESCRIPTION
Looks like GPIO MQTT messages are not retained. 
I'm using a GPIO for a simple door sensor and after a Home Assistant restart, the state of the door is unavailable until the next state change.
There was an issue https://github.com/technyon/nuki_hub/issues/13 a while ago, but seems this affects only the lock messages?

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/technyon/nuki_hub/blob/master/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/technyon/nuki_hub/blob/master/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/technyon/nuki_hub/issues)
- [x] Searched the problem in [discussions](https://github.com/technyon/nuki_hub/discussions)
- [x] Searched the problem in the [docs](https://github.com/technyon/nuki_hub)
- [x] Searched the problem in the [chat](https://discord.gg/9nPq85bP4p)
- [x] Device used (e.g., ESP32-S3): ESP32
- [x] Nuki Hub binary firmware version number used: 9.05-master5
  - [x] Pre-compiled
  - [ ] Self-compiled
- [ ] Provide the output of http://nukihubIP/info:
```
------------ GPIO ------------
GPIO 19: General input (Pull-up)
```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by iranl** [comment]
Added the option to retain GPIO state for inputs in #569.

Enable on the GPIO page in the web configurator.
Feature will be in 9.05-master6 (auto released in a couple of hours)
