### ISSUE TITLE
Support for battery level nuki door sensor

### ISSUE THREAD

**Issue by KitHubek** [technyon/nuki_hub#57]
is possible to add support for door sensor?

https://nuki.io/en/door-sensor/

**Comment by technyon** [comment]
The door sensor is already supported.

**Comment by KitHubek** [comment]
i think this is binary_sensor.NAMEi_door_sensor ?
I mean about battery door sensor

**Comment by technyon** [comment]
Hi, sorry I misread your post. There's no direct support for the battery level in the bluetooth API, only a bit signalling critical battery state. Yes, support for this can be added, but it'll only be battery good yes/no.

**Comment by KitHubek** [comment]
ok, if possible, please add this option. Thi will be battery state: critical or good? If this is possible, this will better than nothing. thanks

**Comment by technyon** [comment]
Check Release 6.6

**Comment by KitHubek** [comment]
i mean that this sensor, door sensor battery is: binary_sensor.NAME_keypad_battery_low ?
And if yes, what if i install keypad v2 - i planned it

**Comment by technyon** [comment]
Yes it should show up under a proper name though. I haven't seen any API changes for v2, so my guess is it'll be the same. If you try it please let me know if it works.

**Comment by KitHubek** [comment]
ok, i will write when i got one. thanks

**Comment by KitHubek** [comment]
fornow closed
