### ISSUE TITLE
Featurerequest: Open door command

### ISSUE THREAD

**Issue by Sab3rRid3r** [technyon/nuki_hub#66]
Hello, I use the nuki hub to integrate a NUKI Smart Lock 3.0 in homeassistant. First of all, thank you for the development of the bridge. The installation worked without any problems.

To be able to use the nuki hub fully, I would be happy if it could be extended with the possibility to open the door.
Greetings
Andreas

**Comment by technyon** [comment]
It's already there, I refer you to the thread in the home assistant forum:

https://community.home-assistant.io/t/nuki-hub-firmware-for-the-esp32/417572/137?u=technyon

**Comment by Sab3rRid3r** [comment]
Oh yeah, thank you very much. The lock.open service works!
