### ISSUE TITLE
Add to README.md description of all hub options and settings

### ISSUE THREAD

**Issue by KitHubek** [technyon/nuki_hub#71]
I see that many people askind here:

```
what do funnction xx?
what is xx?
```

I mean about options in web interface that the user can set or change, for examplpe: 

```
Network Timeout until restart
Restart on disconnect
Restart timer
...
...
...
```

Many options are clear, but i think not for everyone. For me too some options are unclear and incomprehensible and i must do test to know how its working. an explanation of all these settings does not exist in the README file

I think taht good idea is add to README explanation of all options or make some wiki?

**Comment by bcutter** [comment]
Exactly. Some features (config options) should really be explained a bit. Either by adding a small subtitle directly to the option or at least at https://github.com/technyon/nuki_hub#readme.

https://community.home-assistant.io/t/nuki-hub-firmware-for-the-esp32/417572/224

**Comment by technyon** [comment]
It's on my todo list, but there are also issues to fix, and I have to choose what to do first.
