### ISSUE TITLE
Wrong unit of measurement for Signal Strength in Home Assistant

### ISSUE THREAD

**Issue by alexdelprete** [technyon/nuki_hub#72]
HA is logging an error for the BT/WiFi signal strength sensors:

```
Entity sensor.portoncino_bluetooth_signal_strength (<class 'homeassistant.components.mqtt.sensor.MqttSensor'>) is using native unit of measurement 'db' which is not a valid unit for the device class ('signal_strength') it is using; Please update your configuration if your entity is manually configured
```

The unit of measurement for device class `signal_strength` should be (case sensitive) `dB` or `dBm`

![image](https://user-images.githubusercontent.com/7027842/211805868-285af1a7-497c-422c-b49e-27d52e649262.png)

Documentation: https://developers.home-assistant.io/docs/core/entity/sensor

**Comment by technyon** [comment]
Changed and will be included in the next release

**Comment by alexdelprete** [comment]
@technyon I upgraded to 6.11, but I still see dB as unit of measurement for both wifi and bt signal strength.

![image](https://user-images.githubusercontent.com/7027842/212501588-bc7fed30-e316-499c-8642-b04242e38ed7.png)
![image](https://user-images.githubusercontent.com/7027842/212501589-22a793b5-4f6f-478b-929c-2655122b46d0.png)

**Comment by Mincka** [comment]
Actually, `dB` was maybe not the correct unit. I saw this when using ESPHome sensors for Wi-Fi and BT.
They use `dBm` for `SIGNAL_STRENGTH_DECIBELS_MILLIWATT`, for Wi-Fi and BT.
That's also what the devs use in the Android App for Wi-Fi RSSI.

See:
https://github.com/home-assistant/core/blob/master/homeassistant/const.py#L917-L919

**Comment by alexdelprete** [comment]
It's a known controversial topic, particularly since WiFi came out:

![image](https://user-images.githubusercontent.com/7027842/214599184-bda6419c-13ab-408d-a34d-b872868c68a5.png)

To sum it up:

- RSSI should be a positive index: 0-255 (802.11 standard)
- Received Signal Power: is an absolute value, measured in dB, or dBm on a logarithmic scale

So it doesn't matter how HA devs are using it, but what the ESP32 values represent and if it's a log. scale.

**Comment by technyon** [comment]
So should we remove the unit altogether?

**Comment by alexdelprete** [comment]
> So should we remove the unit altogether?

No, it MUST have a UoM. We should check ESP32/Arduino docs to see what the value represents in this specific case. The unit of measure can be dB or dBm.

Look here, they describe RSSI using dB, then give examples in dBm. :)

![image](https://user-images.githubusercontent.com/7027842/214617944-541fec77-a547-4931-8674-7795479e9aa7.png)

So it really depends on the ESP32 SDK you're using...

**Comment by alexdelprete** [comment]
> So should we remove the unit altogether?

nope, we should check what the ESP32 value really represents, and also if it's in dB or dBm. :)

I checked espressif API [docs](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/network/esp_wifi.html#_CPPv427esp_wifi_set_rssi_threshold7int32_t) for ESP32:

![image](https://user-images.githubusercontent.com/7027842/214619314-27303e9d-f185-45a5-be42-ea22c56b078c.png)

So I'd say let's go with `dBm`. :)

**Comment by alexdelprete** [comment]
Jan, is this used for automatic reconnects?

![image](https://user-images.githubusercontent.com/7027842/214621419-37fffe66-4254-4e15-b643-fc786752e582.png)
