### ISSUE TITLE
Extraneous topics (when certain accessories are not used)

### ISSUE THREAD

**Issue by mundschenk-at** [technyon/nuki_hub#84]
- `nuki/battery/keypadCritical`
- `nukiopener/lock/doorSensorState`

Some autodiscovery topics might also be affected, I didn't look at those.

**Comment by technyon** [comment]
The keypad node should be fixed in the latest release. Adding door sensor or not can be discussed. If not available, it should reflect this in the door sensor node, so it's not wrong to publish it.

**Comment by iranl** [comment]
Door Sensor and Keypad entities will not appear in HA discovery if no door sensor or keypad is paired to the Nuki Opener/Lock respectively.

@mundschenk-at:
Is there still a request to remove/disable any possibly extraneous topics in MQTT?

Or is it ok to close this as won't fix?

**Comment by mundschenk-at** [comment]
I will have a look at what is now published. Might take until next week though.

**Comment by iranl** [comment]
Any update?
