### ISSUE TITLE
NukiKeypad not seen by Nuki Hub 7.1

### ISSUE THREAD

**Issue by tca22** [technyon/nuki_hub#92]
I am using NukiOpener, NukiKeypad and Nuki Hub 7.1 .

There are MQTT messages for NukiOpener (nukihub:nukiopener) but nothing for NukiKeypad. There is no "Enabled keypad control via MQTT" in the WebUI.

Did I miss something? Should it be possible to manage NukiKeypad through Nuki Hub 7.1?

**Comment by technyon** [comment]
The keypad is unfortunately only implemented for the lock at this time.

**Comment by tca22** [comment]
ok - kindly request this feature for a future update...

**Comment by knorrre** [comment]
Same problem here: There is no "Enabled keypad control via MQTT" in the WebUI.
https://i.imgur.com/54suCV5.png

**Comment by cpvbruno** [comment]
Hey, sorry, it's not clear to me, in the readme file says the keypad can be managed using the hub but I also don't see "Enabled keypad control via MQTT" in the web UI, is the readme file not updated?

**Comment by technyon** [comment]
Check the latest release, keypad for opener is added.

**Comment by tca22** [comment]
Thanks technyon!!

Not sure if I missed something, but is there any checkbox to select?
I'm  on V8.7 (with Nuki-Opener & Nuki-Keypad) but there is no MQTT message from the keypad coming through, nor can I see something on FHEM [MQTT2_DEVICE].
Any thoughts?

**Comment by technyon** [comment]
It's a bug unfortunately. You only see they option if the keypad is connected to the lock. It'll be fixed in the next release.

In the meantime you should be able by passing the correct parameter in the URL like this:

http://<NUKI_HUB_IP>/method=get?KPENA=1

**Comment by tca22** [comment]
Works! Thank you!!!

**Comment by tca22** [comment]
kindly ask for clarification:

Are the MQTT-topics "battery voltage" and "battery critical" used for the keypad as well?
Should they appear as "nukihub:nukiopener/keypad/battery/..."?
Not sure if NUKI-API provides this information in first place, so it might not be possible to forward at all...

**Comment by technyon** [comment]
You'll find it under battery/keypadCritical. For the keypad there's no level indication, only critical or not.
