### ISSUE TITLE
Unresponsive / crashing after upgrade to 7.2

### ISSUE THREAD

**Issue by ruimarinho** [technyon/nuki_hub#93]
Hi,

I've just upgraded from 6.8 to 7.2 in my LOLIN ESP32 device and it has become very unresponsive. The WiFi interface is now loading very, very slowly (10+ seconds) and the device has trouble reconnecting to WiFi once power is cycled. The OTA update also resulted in the device going into AP mode again, although my previously selected SSID was shown on WiFi Manager.

Sometimes the device will enter a state where MQTT actions are submitted but ignored and the only message that gets posted via MQTT is the device's uptime:

```
2023-01-24T14:21:12+0000 : 0 : 0 : nuki/lock/action unlock
2023-01-24T14:21:23+0000 : 0 : 0 : nuki/maintenance/uptime 9
2023-01-24T14:21:54+0000 : 0 : 0 : nuki/maintenance/uptime 10
2023-01-24T14:22:24+0000 : 0 : 0 : nuki/maintenance/uptime 10
2023-01-24T14:22:55+0000 : 0 : 0 : nuki/maintenance/uptime 11
2023-01-24T14:23:24+0000 : 0 : 0 : nuki/maintenance/uptime 11
2023-01-24T14:23:54+0000 : 0 : 0 : nuki/maintenance/uptime 12
2023-01-24T14:23:57+0000 : 0 : 0 : nuki/lock/action unlock
2023-01-24T14:24:04+0000 : 0 : 0 : nuki/lock/action lock
2023-01-24T14:24:08+0000 : 0 : 0 : nuki/lock/action unlock
```

Anything I can do to help debug these issues? The reason why I upgraded from 6.9 was because the ESP32 would stop accepting commands after a few days (maybe weeks) of operation, and only a power cycle would fix it.

**Comment by mundschenk-at** [comment]
Have you tried reflashing over USB?

**Comment by ruimarinho** [comment]
Yep, that was the first thing I did.

**Comment by technyon** [comment]
Try erasing the flash before re-flashing if you haven't done so already.

**Comment by ruimarinho** [comment]
Just tested on a brand new LOLIN D32 in case hardware could be at fault here but I'm experiencing the same problems. Giving 6.11 a go.

**Comment by technyon** [comment]
What about 7.0 ?

**Comment by technyon** [comment]
I'm not sure about the double subscription - the firmware subscribes on connect that's all it can do. Maybe it's the broker that still keeps the old subscriptions?

To change the naming you should change the MQTT path for the lock.

**Comment by ruimarinho** [comment]
That's what I was referring to, sorry. These are messages published to the broker so I don't think there is a relationship with any sort of subscription.

**Comment by technyon** [comment]
So if you mean that after changing the mqtt path to "home" the old topics still exist, this is to be expected. A client can only create new topics, not delete existing ones. So if you change the path, you have to manually delete the old topics.

**Comment by technyon** [comment]
Please recheck with 8.0

**Comment by technyon** [comment]
Closing, please reopen if not fixed
