### ISSUE TITLE
allow configuration of nuki name used for HASS discovery

### ISSUE THREAD

**Issue by leo-b** [technyon/nuki_hub#99]
Hi!

Please consider a configuration option for `_nukiConfig.name` which is used in publishHASSConfig as device name and part of all sensor entities.
The current name seems to be the display name configured at the nuki lock itself and it looks like it is set at pairing time.
Batch renaming all entities in home assistant doesn't work very reliable and everything gets broken again when re-pairing the lock.

Cheers,
--leo

**Comment by technyon** [comment]
It's not pairing time, but whatever name you've set when the firmware boots up and reads the config from the lock. So if you have multiple locks, just name them differently and you're good.

**Comment by leo-b** [comment]
OK, sorry.
When examining the issue, I changed the _display name_ in the nuki app, not the _device name_.

Now the new device name has been correctly published in the HASS config and being able to specify a separate device name and display name in the nuki app solves my problem.
Thanks!
